### ISSUE TITLE
May help to enable DOT11KVR

### ISSUE THREAD

**Issue by 0093Axis** [lukasz1992/asuswrt-xiaomi#102]
https://github.com/padavanonly/rt-n56u
This padavan fork uses the same 5.0.4.0 driver and successfully enables the DOT11KVR feature.
Depending on the relationship between asuswrt and padavan, I think this may help you with your modifications.

**Comment by lukasz1992** [comment]
I can enable on all drivers, but Asuswrt does not expose interface to use it.
