### ISSUE TITLE
About R2100 Compile Help

### ISSUE THREAD

**Issue by hululu1068** [lukasz1992/asuswrt-xiaomi#103]
I tried to compile R2100 according to README.TXT, but it didn't work.
I can't find the config file for R2100.
Can you list the instructions for compiling in Ubuntu?
Thank you very much!

**Comment by lukasz1992** [comment]
Hi, what is the problem exactly? Procedure is the same as with GPL dump

**Comment by hululu1068** [comment]
I am learning to build for the first time.
Can you list down the detailed build steps.
Thanks!

**Comment by lukasz1992** [comment]
https://github.com/lukasz1992/asuswrt-xiaomi/blob/master/README.TXT
