### ISSUE TITLE
Moving to AsusWRT-Merlin fork

### ISSUE THREAD

**Issue by jokubasver** [lukasz1992/asuswrt-xiaomi#104]
Hi, have you had any thoughts of using the Merlin fork of AsusWRT? Not sure if that's even possible with MT7621, but it could add some more features to tinker around with.

**Comment by lukasz1992** [comment]
Hi, never used. I have not found source code for it.

**Comment by jokubasver** [comment]
https://www.asuswrt-merlin.net/source

**Comment by lukasz1992** [comment]
Those repos do not contain GPL for Mediatek devices (only BRCM)
