### ISSUE TITLE
Going back from AsusWRT to OpenWrt

### ISSUE THREAD

**Issue by systematicat** [lukasz1992/asuswrt-xiaomi#105]
Hi lukasz1992! 
Thanx for your work! 
Due to testing reasons, I like to go back and forth with different fws. 
Can you tell me how to go back to OpenWrt?

**Comment by lukasz1992** [comment]
Hi, which device?

**Comment by systematicat** [comment]
> 

Xiaomi 4A gigabit

**Comment by lukasz1992** [comment]
Please flash openwrt image directly to OS1

**Comment by lukasz1992** [comment]
Yes, I think so

**Comment by systematicat** [comment]
> Yes, I think so

Somethigs is wrong. 
All I can get with that command is Segmentation Fault while mtd-write

**Comment by lukasz1992** [comment]
Sorry, mistake: 
```
mtd-write -i owrt_initramfs-kernel.bin -d linux
reboot -f
```

**Comment by systematicat** [comment]
> Sorry, mistake:
> 
> ```
> mtd-write -i owrt_initramfs-kernel.bin -d linux
> reboot -f
> ```

Thank you @lukasz1992 ! 
This is correct command. Flashed without any problems.
