### ISSUE TITLE
OpenVPN client doesn't work 

### ISSUE THREAD

**Issue by asuzdal** [lukasz1992/asuswrt-xiaomi#108]
Today flashed your firmware on the Global ver. R4A. Tried to configure vpn client by the NordVPN [tutorial](https://support.nordvpn.com/Connectivity/Router/1047410562/How-to-configure-your-Asus-router-running-original-firmware-AsusWRT.htm), but connection always fails, sys log shows the following error: `vpnclient5: Get CA failed`

**Comment by lukasz1992** [comment]
Message comes from prebuilt binary. I could only check your settings, no source code modifications.

Please share your config with redacted keys, so I could check it.

**Comment by lukasz1992** [comment]
Please select checkbox (opposite to instruction) and paste CA certificate in Import CA file.

**Comment by asuzdal** [comment]
[Link](https://www.dropbox.com/s/9j73g2od0codhpb/Screen%20Recording%202021-12-14%20at%2016.10.47.mov?dl=0) to the config files (cert and key removed)

**Comment by asuzdal** [comment]
I saw a similar [issue](https://github.com/lukasz1992/asuswrt-xiaomi/issues/94) with OpenVPN server configuration. 
Logs showed the same error.

**Comment by lukasz1992** [comment]
Possibly something is wrong with webserver, that can not upload ca.crt.
You can try 'manual setting' and paste key there.

Note: CA is not a secret.

**Comment by asuzdal** [comment]
Tried, the same result( 
I switched from OpenWRT firmware, it had poor network speed with OpenVPN configuration.

**Comment by asuzdal** [comment]
Also found an interesting [graph](https://openwrt.org/docs/guide-user/services/vpn/openvpn/performance). This router has an mt7621 processor and its maximum is 20Mbit/s. I would prefer to use a NordVpn desktop client, it doesn't reduce network speed as much as a router OpenVPN client.

**Comment by lukasz1992** [comment]
We could possibly try manually set CA with nvram.

OpenVPN is generally slow, because of tun driver.
You could use wireguard (which works entirely in kernel driver) that is much faster.
NordVPN supports wireguard. But you would need to manually implement scripts and compile both driver and userspace tools
