### ISSUE TITLE
Rebase to RT-AX53U GPL

### ISSUE THREAD

**Issue by lukasz1992** [lukasz1992/asuswrt-xiaomi#109]
Improvements:
- newer kernel
- newer samba
- probably more

Problems:
- slow NTFS drivers (could try to backport new ntfs3 kernel driver using this https://svn.dd-wrt.com/browser/src/router/ntfs3)

**Comment by paldier** [comment]
the real problem, no init-ralink.c and ralink.c codes

**Comment by lukasz1992** [comment]
@paldier Have not noticed yet, maybe could port from current (RT-AC85U).

**Comment by paldier** [comment]
https://github.com/LGA1150/ntfs3-oot

**Comment by lukasz1992** [comment]
thank you, dd-wrt already backported to 4.4.

**Comment by paldier** [comment]
https://github.com/SWRT-dev/rtax53u/blob/master/release/src/router/rc/sysdeps/init-ralink.c.bak
I'm not sure if it is completely correct.

**Comment by anvikVRN** [comment]
Need WireGuard and asuswrt for Mi4 . Can test it, have 4a and 4. Thnx for your work

**Comment by lukasz1992** [comment]
No time and money to do it at this moment.
