### ISSUE TITLE
Questions about 4A Gigabit with Breed+Padavan

### ISSUE THREAD

**Issue by hav4k** [lukasz1992/asuswrt-xiaomi#110]
Hi.

I have this router of Xiaomi with Breed and Padavan, wanna try AsusWRT... but i need fully working WakeOnLan, VLAN tag and OpenVPN server. Is this firmware suitable and stable? Can install it with Breed or maybe SSH? Thanks for reply and good work. 

For now, i will check wiki and issue:

https://github.com/lukasz1992/asuswrt-xiaomi/wiki/Installation#padavan

https://github.com/lukasz1992/asuswrt-xiaomi/issues/94

Regards.

**Comment by lukasz1992** [comment]
Hi, I do not give any guarantee. WOL should work, I do not know about VLAN, OpenVPN should work.

**Comment by lukasz1992** [comment]
Possible that OpenVPN server needs CA cert to be set manually, has not tested it.
