### ISSUE TITLE
Mesh and roaming using  openwrt code

### ISSUE THREAD

**Issue by p4c0ga** [lukasz1992/asuswrt-xiaomi#112]
Recently, I have seen this information for openwrt, giving 802.11s support to MT7621 chipsets with MT603, 612 and 615 radios ...
Would it be possible to enable mesh with this info ?
It would also be nice to implement 802.11r for fast roaming between mesh nodes.
Openwrt has the code for all this.
Thanks uin advance

**Comment by lukasz1992** [comment]
Unfortunately 3.0.0.4.382 branch of AsusWrt does not support Mesh.
AsusWrt also never gave any options for 802.11r/k/v.

I do not use mt76 driver.

**Comment by p4c0ga** [comment]
Thankssss
