### ISSUE TITLE
Can't login after flashing

### ISSUE THREAD

**Issue by infinitas-x** [lukasz1992/asuswrt-xiaomi#113]
Hi.

Firmware: RT-MIR4A_3.0.0.4_382_52301-geac6f28.trx
I tried to reset router, but it didn't work!

Is LAN DHCP off?
I can't find the following informations:
LAN IP:
Login username and password:
WiFi password:
Please tell me, thanks!

**Comment by lukasz1992** [comment]
DHCP should be on; wifi should have no password.

Without logs I can not tell you what went wrong.

**Comment by infinitas-x** [comment]
I don't know how to find logs.

I'm on OEM 2.28.69 and maybe following will help.

Flash: GigaDevice GD25Q128

```
root@XiaoQiang:~# nvram show | sort
Router_unconfigured=0
boot_wait=off
bootcmd=tftp
bootdelay=5
ethaddr="00:AA:BB:CC:DD:10"
flag_boot_rootfs=0
flag_boot_success=1
flag_boot_type=2
flag_last_success=0
flag_ota_reboot=0
flag_try_sys1_failed=0
flag_try_sys2_failed=0
ipaddr=192.168.31.1
mode=Router
model=R4A
no_wifi_dev_times=0
normal_firmware_md5=eeb68c46e84b2e403ad724f65543601c
nv_sys_pwd=***
nv_wan_type=dhcp
nv_wifi_enc1=mixed-psk
nv_wifi_enc=mixed-psk
nv_wifi_pwd1=***
nv_wifi_pwd=***
nv_wifi_ssid1=Xiaomi_5G
nv_wifi_ssid=Xiaomi
restore_defaults=0
serverip=192.168.31.100
stderr=serial
stdin=serial
stdout=serial
telnet_en=0
uart_en=0
wl0_radio=1
wl0_ssid=Xiaomi_5G
wl1_radio=1
wl1_ssid=Xiaomi

root@XiaoQiang:~# mtd -e OS1 -r write /tmp/MIR4A.trx OS1
Unlocking OS1 ...
Erasing OS1 ...

Writing from /tmp/MIR4A.trx to OS1 ...
Rebooting ...
```

**Comment by lukasz1992** [comment]
It is possible that firmware image is broken - but I do not have hardware to test it.
If 52302 release does not work for you I can only delete image; hoping someone could test it with console access.

**Comment by infinitas-x** [comment]
I tried 52302 before, the same problem.

I found this link, firmware is 52289.
https://www.right.com.cn/forum/thread-4057796-1-1.html
Can you give 52289 to me for test?

Bty, I found another link, firmware base on 52291, be modified for breed.
https://www.right.com.cn/forum/thread-6071098-1-1.html
After flashing by breed, it works fine.

**Comment by lukasz1992** [comment]
I do not have the firmware anymore, someone has to build it.
