### ISSUE TITLE
Cant install "download master" on mi3g device with 3.0.0.4_382_52302

### ISSUE THREAD

**Issue by element3309** [lukasz1992/asuswrt-xiaomi#116]
Hi, just tried your firmware, thank you! Unfortunately I can't use the download master.
<img width="496" alt="1" src="https://user-images.githubusercontent.com/59870129/150635982-3d35b8da-5d83-4f4f-925d-db90a4023c71.png">
<img width="380" alt="2" src="https://user-images.githubusercontent.com/59870129/150635987-c7382828-708d-421c-a8a3-686741e3b95a.png">
last log lines:
Jan 22 14:03:14 crond[329]: time disparity of 1955877 minutes detected
Jan 22 14:03:38 Mastiff: exit.
Jan 22 14:03:42 kernel: mt76x2_calibration(channel = 58)
Jan 22 14:03:51 rc_service: httpd 330:notify_rc start_apps_install downloadmaster sda1

**Comment by lukasz1992** [comment]
Hi, Asus released faulty repository.
One workaround you can try:
1. Wait installation to fail
2. Login to console and run these commands
```
sed 's/Package: ncurses/Package: ncursey/g' -i /opt/lib/ipkg/lists/optware.asus
sed 's/Package: libevent/Package: libeveny/g' -i /opt/lib/ipkg/lists/optware.asus
ipkg install libevent ncurses
```
3. Try again to install from UI
