### ISSUE TITLE
AiMesh Support?

### ISSUE THREAD

**Issue by oscarliuyc** [lukasz1992/asuswrt-xiaomi#117]
Hi, this firmware gives a 2nd life to my xiaomi r3p router.  Great thanks really.  I have an RT-AC86U.  I know that the latest firmware of ASUSWRT-Merlin does support AiMesh even on non-ASUS routers.  Is it possible to update this branch to the latest merlin version?

Million thanks

**Comment by lukasz1992** [comment]
Hi,

If it was possible, Asuswrt-merlin would support ralink devices and have it already. Even if MTK drivers support apcli, current branch (.382 does not support any meshing at all).
So, the answer is not possible at all :(

**Comment by oscarliuyc** [comment]
many thanks
