### ISSUE TITLE
breed bootloader dont work asuswrt

### ISSUE THREAD

**Issue by kissmorning** [lukasz1992/asuswrt-xiaomi#118]
boot flash 0x600000 - 0x200000
Even though I tried the values with breed, the software does not load. This topic has been brought up before. I couldn't find a solution

**Comment by kissmorning** [comment]
version that works fine
RT-MIR3G_3.0.0.4_382_52113-b6d7d8f4.trx

this version cannot be installed with breed

**Comment by lukasz1992** [comment]
Do you have a log from serial console?

Is it possible you have bad sectors in NAND? Could you provide bootlog even with older version? I do not have old version now.

**Comment by kissmorning** [comment]
I have the old version. all software can be installed only asuswrt is not installed..

padavan,openwrt,keenetic ..

**Comment by lukasz1992** [comment]
Please provide log from padavan

**Comment by kissmorning** [comment]
Jan  1 00:01:50 httpd[515]: Firmware update: Incorrect image ProductID: RT-MIR! Expected is MI-R3G.

**Comment by jokubasver** [comment]
I'm running RT-MIR3G_3.0.0.4_382_52302-geac6f28.trx on my Xiaomi Router 3G using Breed and it works just fine. I did have to edit the path in Breed (one of the menus on the side of the interface): [autoboot.command boot flash 0x200000](https://user-images.githubusercontent.com/20933693/64078902-ff3fdb80-ccb6-11e9-9bc6-f6bff1849125.png)

**Comment by kissmorning** [comment]
RT-MIR3G_3.0.0.4_382_52113-b6d7d8f4.trx

version dont work with breed

**Comment by kissmorning** [comment]
I was using this software in advance. But the recent installation was very difficult and there are many problems. I have stopped using this software, you can close the problem page.
