### ISSUE TITLE
Cyclops Blink vulnerability

### ISSUE THREAD

**Issue by jokubasver** [lukasz1992/asuswrt-xiaomi#125]
It seems like the latest version of this firmware is vulnerable to Cyclops Blink: https://www.asus.com/content/ASUS-Product-Security-Advisory/
Firmware versions under 3.0.0.4.386.xxxx are affected, so this port should be as well.

Is a patch or a newer firmware of this port possible?

**Comment by lukasz1992** [comment]
I do not know the attack vector and I do not see ralink/mediatek devices on that list.

Let's select any model from that list, wait until Asus releases new firmware and GPL for it and then I could check and fix vulnerability in this repo if there is any.
