### ISSUE TITLE
Firmware Update to the newest version

### ISSUE THREAD

**Issue by St4mi** [lukasz1992/asuswrt-xiaomi#126]
Hello there and first of all thank you for your great work!
I am running version 3.0.0.4_382_52302 on my RM2100 and it works perfect.
Now I see you have updated it to 3.0.0.4_382_52400 and want to update it.
Can I just take the RT-RM2100_3.0.0.4_382_52400-geac6f28.trx and update it through the web interface?
http://router.asus.com/Advanced_FirmwareUpgrade_Content.asp
Or do I have to flash it like the first time through SSH?

thanks and best regards
Stami

**Comment by lukasz1992** [comment]
Hi, Flashing through web interface is fine and should work.

But note I do not have this device anymore and coult not test release.

**Comment by St4mi** [comment]
Thank you.
