### ISSUE TITLE
谢谢作者的幸苦付出，这个usb挂载似乎有点问题

### ISSUE THREAD

**Issue by mizhihan** [lukasz1992/asuswrt-xiaomi#127]
一点挂载就会是路由器死机重启，不知是不是普遍问题

**Comment by lukasz1992** [comment]
I do not know chineese, please submit ticket in english

**Comment by mizhihan** [comment]
Thank you for your hard work.There seems to be a problem with this USB mount. A little mount will cause the router to crash and restart. I wonder if it is a common problem
