### ISSUE TITLE
A few more questions about RM2100 and Toshiba Nand

### ISSUE THREAD

**Issue by kilroy98** [lukasz1992/asuswrt-xiaomi#128]
Hello, I looked in the files **nand_device_list.h** and **nand_ids.c**, and did not see my memory there. Maybe because of this the firmware can not be loaded?
Redmi AC2100 is sold with ESMT or Toshiba nand flash.
I can make a pull request with information about my chip, it may just need to correct the data in the **nand_device_list.h** file, because I'm not sure that everything will be specified correctly.

**Comment by lukasz1992** [comment]
nand_device_list.h is just for printing a nice name. If detection fails, generic profile is used, which should also work correctly and without any loss. That's also my expirience with ESMT chips.

You can send the patch here, I would see if it changes anything regarding to boot issue.

It is more probable that Toshiba chip has bad sectors which this version does not really handle - and that could be a reason why you can not boot. Could you show me `dmesg` from other firmware to check which sectors are bad?

**Comment by kilroy98** [comment]
It's for nand_ids.c
```
{"TC58BVG0S3H 1G 3.3V 8-bit",
		{ .id = {0x98, 0xf1, 0x80, 0x15, 0xf2, 0x16, 0x08, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
	{"TC58NVG0S3H 1G 3.3V 8-bit",
		{ .id = {0x98, 0xf1, 0x80, 0x15, 0x72, 0x16, 0x08, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
	{"TC58NVG0S3E 1G 3.3V 8-bit",
		{ .id = {0x98, 0xd1, 0x90, 0x15, 0x76, 0x14, 0x01, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
```
And it's for nand_device_list.h. But I'm not sure if 0x00844333 is correct
```
{0x98F1, 0x8015F2, 4, 8,  128, 128, 2048,  64, 0x00844333, "TC58BVG0S3H", 0},
	{0x98F1, 0x801572, 4, 8,  128, 128, 2048,  64, 0x00844333, "TC58NVG0S3H", 0},
	{0x98D1, 0x901576, 4, 8,  128, 128, 2048,  64, 0x00844333, "TC58NVG0S3E", 0},
```
My nand model is TC58BVG0S3H. I don't know why, but `dmesg` not show full loading log and i looked this from system log in WEB (AsusWRT by paldier). Or is this not what you need?
>kernel: Bad eraseblock 14 at 0x0000001c0000
>kernel: Bad eraseblock 15 at 0x0000001e0000
>kernel: Bad eraseblock 768 at 0x000006000000

And I also propose to bring nand_device_list.h to such a form as here. I think it's more readable. https://github.com/kilroy98/ac85p-asuswrt/blob/master/release/src-ra-5010/linux/linux-3.10.14.x/drivers/mtd/nand/nand_device_list.h

**Comment by lukasz1992** [comment]
I am afraid that those eraseblock make this firmware not working at all.
I am not sure how other drivers handle these bad sectors (remap or what), but Asus version of driver seems to not support it.

Possibly you could reconfigure partition mapping and recompile source code.
Or you need to do full **low-level** flash dump, to make sure how implementation should work.

**Comment by kilroy98** [comment]
I think I have not enough knowledge to do this :(

**Comment by lukasz1992** [comment]
Tried to check drivers, they already have SKIP_BAD_BLOCK enabled. Maybe Asus has diffrent logic for it, do not know :(

**Comment by lukasz1992** [comment]
Problem should be fixed with the new release
