### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Deathmotorchik** [lukasz1992/asuswrt-xiaomi#129]
Hi, I'm using your firmware on Xiaomi Redmi AC2100, I installed a new release as an update via the web interface and in the Wi-Fi settings I lost the ability to select a channel, the ,,auto" is standing and does not respond, is it possible to solve it somehow? Sincerely.

**Comment by lukasz1992** [comment]
Could you check if this is only for 5GHz WiFi or 2GHz WiFi too?

**Comment by lukasz1992** [comment]
Issue should have gone with latest master.

Could you help me to check if other issue is present - I mean if running commands:
stainfo_2g and stainfo_5g work or not?

**Comment by Deathmotorchik** [comment]
I checked that it is also impossible to switch to 2.4g.

**Comment by Deathmotorchik** [comment]
On this version, everything was fine 3.0.0.4_382_52302, was it necessary to reset to factory settings after the update?

**Comment by lukasz1992** [comment]
I rebuild this firmware and will reupload images soon. It'd be necessary if you used WPA3.

**Comment by Deathmotorchik** [comment]
It's good! Thanks for the answer. I use wpa2.

**Comment by lukasz1992** [comment]
Please check again, I pushed updated images.

**Comment by Deathmotorchik** [comment]
OK

**Comment by Deathmotorchik** [comment]
Man! Everything is good! The channel switch is working. Thank you for the quick solution to the problem!
