### ISSUE TITLE
Xiaomi Redmi AC2100 with Toshiba NAND

### ISSUE THREAD

**Issue by IXLShidzua** [lukasz1992/asuswrt-xiaomi#130]
Hello lukasz1992.  I (as well as another person) have run into some bad blocks in my Toshiba memory. Because of this, your firmware just doesn't work. But ferhung-mtk also has his own version of AsusWRT, which he was able to adapt to the bad memory of this router. He even wrote how he did it - https://github.com/ferhung-mtk/asuswrt_RM2100/commit/3620d9fb54b8dc3ea6a6fd23541869b7f9bfad63 Maybe you can try to do the same for Us? This person also mentioned in his solution that you helped him to solve the problem.

**Comment by lukasz1992** [comment]
Actually I made this part of code, but code was very ugly and removed it in my repo.

I had no time to work with DUAL_IMAGE Asus flag and previously used solution you mentioned. Even if it has booted from different flash offset (second image), second config partition is not supported at all.
So in that case router would not be able to boot too.

Basically his firmware probably has different location on config partition, that's why it works
You could recompile image and select other sectors to solve the issue - but I am unsure why these specific sector are bad very often.

**Comment by IXLShidzua** [comment]
The big problem is that I'm not an expert at this, and I have no idea how to reassign sectors so that the firmware works. I tried to compile your firmware on Ubuntu 20.04 LTC, but I got different Makefiles related errors.

**Comment by lukasz1992** [comment]
If you use Breed bootloader, you could flash padavan and dump whole content (128MB) of flash - I could check what exactly happens.

**Comment by kilroy98** [comment]
If it's still relevant, I'll try to do it today. Dump send here?

**Comment by lukasz1992** [comment]
Yes please. With flashed firmware that works, I'll examine what is under bad blocks.

**Comment by lukasz1992** [comment]
Please also show whole ```dmesg``` output after you send flash dump

**Comment by kilroy98** [comment]
https://mega.nz/file/Wh4xwTSb#vVnc-fhI8wjM4AuYeAFICIOCOnHDpRafEtOVEtzo5M8

And dmesg - https://pastebin.com/BLzKCWqS 
(Is this the full log? It's just that I've never used this command and don't know what the output looks like.)

**Comment by kilroy98** [comment]
Unfortunately I can't flash it. Need to somehow reduce the file size to 128MB, because Breed adds some more information to the full dump and the size is more than 128MB and he refuses to flash it

**Comment by kilroy98** [comment]
Maybe you can make a test build?

**Comment by IXLShidzua** [comment]
> Maybe you can make a test build?

I will try to build AsusWRT firmware with shift_on_bbt = 0; parameter tomorrow, and I will send you (if I can build it).

**Comment by IXLShidzua** [comment]
In the mtk_nand.c file there are two references to shift_on_bbt (static int shift_on_bbt = 0 and shift_on_bbt = 1), do I understand correctly that I need to set the value 0 just on the second reference?

**Comment by IXLShidzua** [comment]
I can't get it to compile. Gives out an error - Make: Error 2, after entering the command make rt-rm2100, or make model rt-rm2100 (also does not work). Maybe lukasz1992 will tell me what to do with this error and I can compile.

**Comment by kilroy98** [comment]
@lukasz1992 I tried to take a virtual machine image from Prometheus, hoping that everything needed is installed there, but the compilation of the firmware does not complete, and I do not know how to scroll up to see the error. Maybe you can make a test build with this change? Your computer is already set up to compile the firmware, you will be able to do it faster. Rather than I will try to eliminate all errors, without knowledge of using Linux systems.

**Comment by kilroy98** [comment]
And about the modified full backup, maybe something can be removed from it so that it can be flashed?

**Comment by lukasz1992** [comment]
[RT-RM2100_3.0.0.4_382_52400-geac6f28.zip](https://github.com/lukasz1992/asuswrt-xiaomi/files/8512208/RT-RM2100_3.0.0.4_382_52400-geac6f28.zip)

please try that image.

It is not possible to flash the part of full backup I wanted to modify.

**Comment by kilroy98** [comment]
She's loading O_O But, unfortunately, after a reboot, the firmware loads as just installed, that is, the settings are saved until the reboot
dmesg - https://pastebin.com/LSS54pt0
System Log in WEB UI - https://pastebin.com/xxWL0tvd

**Comment by lukasz1992** [comment]
I do not include UUAccelerator.

Settings are not saved because of bad blocks - all sectors for config partition are bad.
You can change location of config partition and recompile firmware.

**Comment by lukasz1992** [comment]
Need log from serial console to continue work with it (logs you sent are truncated)

**Comment by kilroy98** [comment]
Okay, I'll send them closer to the night, during the day I can't do any manipulations with the router :(

**Comment by kilroy98** [comment]
https://pastebin.com/ULimxD21

> You can change location of config partition and recompile firmware.
Can you tell me where to change it and to what values? And what is needed to compile the firmware (what system, libraries, etc.)?

**Comment by kilroy98** [comment]
```
admin@RT-RM2100:/tmp/home/root# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00100000 00020000 "Bootloader"
mtd1: 00020000 00020000 "nvram"
mtd2: 00020000 00020000 "Factory"
mtd3: 00020000 00020000 "Factory2"
mtd4: 03200000 00020000 "linux"
mtd5: 03055040 00020000 "RootFS"
mtd6: 02800000 00020000 "jffs2"
mtd7: 07f80000 00020000 "ALL"
mtd8: 023d8000 0001f000 "jffs2"
admin@RT-RM2100:/tmp/home/root#
```

**Comment by lukasz1992** [comment]
Thanks, please send also System Log in WEB UI. Let me know if settings are preserved after reboot.

**Comment by kilroy98** [comment]
https://pastebin.com/1zZmCbZ1
Settings are still not saved after rebooting the router :(

**Comment by lukasz1992** [comment]
[RT-RM2100_3.0.0.4_382_52400-geac6f28.zip](https://github.com/lukasz1992/asuswrt-xiaomi/files/8549917/RT-RM2100_3.0.0.4_382_52400-geac6f28.zip)
Please send me System Log in Web UI for this firmware after it boots

**Comment by kilroy98** [comment]
Settings still not saved after reboot.
https://pastebin.com/uSRnT9MV

**Comment by lukasz1992** [comment]
[RT-RM2100_3.0.0.4_382_52401-geac6f28.zip](https://github.com/lukasz1992/asuswrt-xiaomi/files/8553669/RT-RM2100_3.0.0.4_382_52401-geac6f28.zip)

Could you beta-test new release? I appreciate if you test:
- if firmware is able to boot
- restarting (if changes persists)
- connecting/disconnecting 5GHz wifi many times on many devices

**Comment by kilroy98** [comment]
I flashed this version and it loads, but I couldn't test anything else.
When there is a LAN connection, after booting the firmware, the router goes into reboot. I tried to connect to Wi-Fi, I was able to go through the initial setup and the router also went into a reboot and so on in a circle (I think the settings are now saved if the router reboots again after a reboot, and does not redirect me to the initial setup page)

**Comment by lukasz1992** [comment]
[RT-RM2100_3.0.0.4_382_52401-geac6f28.zip](https://github.com/lukasz1992/asuswrt-xiaomi/files/8554857/RT-RM2100_3.0.0.4_382_52401-geac6f28.zip)
Thanks for testing - another (let's see if fixed) version

**Comment by kilroy98** [comment]
No change, also reboots automatically if there is a connection on the LAN port :(

**Comment by lukasz1992** [comment]
[RT-RM2100_3.0.0.4_382_52400-geac6f28.zip](https://github.com/lukasz1992/asuswrt-xiaomi/files/8561654/RT-RM2100_3.0.0.4_382_52400-geac6f28.zip)
Next try?

**Comment by kilroy98** [comment]
Now it loads normally. And even saw my last starting router setting.
https://pastebin.com/rGNQZstY - (It's logs from first boot)

But I did a factory reset to make sure everything boots up fine. And yes, the firmware loads without problems and the settings are saved after a reboot.

https://pastebin.com/tWdrazTv - This log after I did a factory reset, changed the settings for myself and did another reboot.

I also tried to check the connection / disconnection to the 5GHz network, and everything seems to be working fine. (I spammed by connecting between networks 2.4 and 5GHz on two phones).
As for the traffic history, I didn’t quite understand where to look, but I turned on QoS - Web History and everything is displayed there, of course the update is not instant, but the data is displayed. And also I checked Traffic Analyzer - Statistic and the data is also displayed and saved after reboot.

**Comment by kilroy98** [comment]
@lukasz1992 since it was possible to run the firmware with my memory, maybe you can add data to nand_ids.c and nand_device_list.h? My model is `TC58BVG0S3H`.
```
        {"TC58BVG0S3H 1G 3.3V 8-bit",
		{ .id = {0x98, 0xf1, 0x80, 0x15, 0xf2, 0x16, 0x08, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
	{"TC58NVG0S3H 1G 3.3V 8-bit",
		{ .id = {0x98, 0xf1, 0x80, 0x15, 0x72, 0x16, 0x08, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
	{"TC58NVG0S3E 1G 3.3V 8-bit",
		{ .id = {0x98, 0xd1, 0x90, 0x15, 0x76, 0x14, 0x01, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
```
```
        {0x98F1, 0x8015F2, 4, 8, 128, 128, 2048, 64, 0x00844333, "TC58BVG0S3H", 0},
	{0x98F1, 0x801572, 4, 8, 128, 128, 2048, 64, 0x00844333, "TC58NVG0S3H", 0},
	{0x98D1, 0x901576, 4, 8, 128, 128, 2048, 64, 0x00844333, "TC58NVG0S3E", 0},
```
I'm not sure if 0x00844333 is correct.

**Comment by kilroy98** [comment]
Maybe then add only to nand_ids.c? I found this data in other github repositories, I think that everything is correctly indicated there. Or is this file not used in the firmware?
For my memory, I found the data here (the file name is different, but I think it's the same nand_device_list.h): https://github.com/keenetic/kernel-49/blob/134030ace9cdaadb969bdc4aa0e967d2cd7493f2/drivers/mtd/ralink/mt7621_nand.c#L126

I think the data is correct and at least this can be added.

nand_device_list.h:
`{0x98F1, 0x8015F2, 4, 8, 128, 128, 2048, 64, 0x00844333, "TC58BVG0S3H", 0},`

nand_ids.c:
```
        {"TC58BVG0S3H 1G 3.3V 8-bit",
		{ .id = {0x98, 0xf1, 0x80, 0x15, 0xf2, 0x16, 0x08, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
	{"TC58NVG0S3H 1G 3.3V 8-bit",
		{ .id = {0x98, 0xf1, 0x80, 0x15, 0x72, 0x16, 0x08, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
	{"TC58NVG0S3E 1G 3.3V 8-bit",
		{ .id = {0x98, 0xd1, 0x90, 0x15, 0x76, 0x14, 0x01, 0x00} },
		  SZ_2K, SZ_128, SZ_128K, 0, 8, 64},
```
