### ISSUE TITLE
help on how to install via breed or spi 

### ISSUE THREAD

**Issue by andredpe1** [lukasz1992/asuswrt-xiaomi#137]
help on how to install via breed or spi have a xiaomi mi router 4a gigabit, but none of the tested images work when installed via breed, I tried padavan and openwrt both worked perfectly, I tried to update the systems as informed in the wiki, but it didn't work, the router restarts, only the blue led lights up and there is no connection dhcp

**Comment by lukasz1992** [comment]
I do not know why it stopped working, possibly need someone with serial console to help troubleshoot problem. I do not have this device. You could try older releases.

**Comment by andredpe1** [comment]
I don't have the serial console. Github is not providing the previous versions, would you be able to email me some versions?
My email is andredpe1@gmail.com

**Comment by lukasz1992** [comment]
I do not have them anymore

**Comment by lukasz1992** [comment]
Try this one https://github.com/lukasz1992/asuswrt-xiaomi/releases/download/3.0.0.4_382_52302/RT-MIR4A_3.0.0.4_382_52302-geac6f28.trx

**Comment by andredpe1** [comment]
taking advantage of the topic, I would like to know if it is possible to compile something for devices that use qualcomm soc such as ipq4018/4019 , since there are asus devices that use this soc, if possible how would seh development be? I have a limksys ea6350 v3 here.

**Comment by lukasz1992** [comment]
Possible :) But need lot of time to do it or use swrt-dev for example
