### ISSUE TITLE
frequent disconnections with firmware 3.0.0.4_382_52302

### ISSUE THREAD

**Issue by andredpe1** [lukasz1992/asuswrt-xiaomi#138]
frequent disconnections with firmware 3.0.0.4_382_52302
 on mi router 4a, disconnections occur on wifi 2.4ghz and 5.0ghz, another problem to report, the adaptive qos works in only one core thus saturating the connection and only one core, you could try to do irqbalance

**Comment by lukasz1992** [comment]
Please provide me output of ```cat /proc/interrupts``` when you reproduce problem.

**Comment by andredpe1** [comment]
/tmp/home/root# cat /proc/interrupts
           CPU0       CPU1       CPU2       CPU3
  3:          7     532214          0          0  MIPS GIC  eth2
  4:        294          0      19431          0  MIPS GIC  rai0
  7:     115413     115348     115368     115353  MIPS GIC  timer
 12:          0          0          0          0  MIPS GIC  ralink_gpio
 23:          2          0          0          0  MIPS GIC  Ralink_ESW
 24:        588          0          0      35250  MIPS GIC  ra0
 26:       2092          0          0          0  MIPS GIC  serial
 29:          0          0          0          0  MIPS GIC  rt2880_timer1
 30:          0          0          0          0  MIPS GIC  rt2880_timer0
 31:          0          0          0          0  MIPS GIC  rt2880_timer2
 56:       3318          0          0          0  MIPS GIC  IPI_resched
 57:          0       3747          0          0  MIPS GIC  IPI_resched
 58:          0          0       3076          0  MIPS GIC  IPI_resched
 59:          0          0          0       4026  MIPS GIC  IPI_resched
 60:      51781          0          0          0  MIPS GIC  IPI_call
 61:          0       4745          0          0  MIPS GIC  IPI_call
 62:          0          0      52446          0  MIPS GIC  IPI_call
 63:          0          0          0       2739  MIPS GIC  IPI_call

**Comment by andredpe1** [comment]
![image](https://user-images.githubusercontent.com/103959821/171780741-32d81a9a-7155-4128-9ac3-f9aff9d595a1.png)

**Comment by lukasz1992** [comment]
It is hard to tell anything about disconnections without your configs.
It is possible you can improve it and it is possible that drivers are the problem.

I do not own this device and disabled builds for this model - as some people reported boot issues.
