### ISSUE TITLE
Is R3P with SPI/NOR supported with AsusWRT?

### ISSUE THREAD

**Issue by thinhdinh25** [lukasz1992/asuswrt-xiaomi#139]
I 've got a brick R3P by flashing R3G 's Bootloader. I managed to unbrick it by adding a 32mb NOR/SPI flash so i wondered if AsusWRT is supported

**Comment by lukasz1992** [comment]
No, I think that fastest way could be compiling u-boot with support for both NAND and SPI. Or OpenWRT

**Comment by zhzmst2020** [comment]
改了32M闪存后可以刷友讯dir882适配的OpenWrt固件，但nand改spi必须更改电阻的位置。

**Comment by zhzmst2020** [comment]
改32M闪存后可以刷友讯dir882适配的OpenWrt固件，但nand改spi必须更改电阻的位置。

**Comment by thinhdinh25** [comment]
> 改32M闪存后可以刷友讯dir882适配的OpenWrt固件，但nand改spi必须更改电阻的位置。

I don't want to use Openwrt because of its bad wifi power

**Comment by thinhdinh25** [comment]
> No, I think that fastest way could be compiling u-boot with support for both NAND and SPI. Or OpenWRT

I read the wiki and found out that there are SPI support. I can provide console or something you may need. Can you make it be supported
