### ISSUE TITLE
country

### ISSUE THREAD

**Issue by qslfz** [lukasz1992/asuswrt-xiaomi#27]
After modifying the country region,2.4g cannot modify the channel。Can you set the default country region as USA?

**Comment by lukasz1992** [comment]
Not as a default setting. Please enter in console:
```
nvram set wl_country_code=US
nvram set wl0_country_code=US
nvram set wl1_country_code=US
```

After that, navigate to user interface, change channel and save settings from web user interface.
I tried to do it just now, it works.

Actually it is possible to patch code, to allow country selection from UI, I can write how to do that, anyway I currently do not have enough time to test it.

**Comment by NEOs007** [comment]
Please make it possible to change the region and power of the transmitter, this option will be useful for everyone.

**Comment by lukasz1992** [comment]
I will try to do it in my spare time.

**Comment by lukasz1992** [comment]
New firmware supports it. Go to Wireless -> Professional and you should see option in the bottom.
