### ISSUE TITLE
Repeater support

### ISSUE THREAD

**Issue by ferhung-mtk** [lukasz1992/asuswrt-xiaomi#31]
Abourt repeater support, i have some tests in my k2p, it showed well (maybe has some bugs, but working).
First you should add "REPEATER=y PROXYSTA=y" at target.mak.

Then, modify the following files:
`drivers/net/wireless/ralink/mt_wifi/common/cmm_info.c`
`release/src/router/httpd/sysdeps/web-ralink.c`
`release/src/router/rc/sysdeps/ralink/ralink.c`
`release/src/router/shared/sysdeps/ralink/ralink.h`.

In cmm_info.c, you should change `sprintf(msg+strlen(msg), "%-23s", SecurityStr);` as: 
`sprintf(msg+strlen(msg), "%-19s", GetAuthMode((CHAR)ap_auth_mode));`
`sprintf(msg+strlen(msg), "%-6s", GetEncryptType((CHAR)ap_cipher));`
and change `	sprintf(msg+strlen(msg),"%-4s%-33s%-20s%-23s%-9s%-7s%-7s%-3s\n",
	    "Ch", "SSID", "BSSID", "Security", "Signal(%)", "W-Mode", " ExtCH"," NT");` as:
`sprintf(msg+strlen(msg),"%-4s%-33s%-20s%-9s%-16s%-9s%-7s\n",
	    "Ch", "SSID", "BSSID", "Enc", "Auth", "Siganl(%)", "W-Mode");`
then comment out some values of " ExtCH" and " NT".
web-ralink.c, ralink.c and ralink.h should keep the same as above ones.

rc/sysdeps/ralink/ralink.c should use the one of RT-AC1200GU.

**Comment by lukasz1992** [comment]
Have you tried to compile it? I did it some time ago, and some symbols were not resolved - Linker could not link rc executable.

Second thing is I am afraid of bugs.

**Comment by ferhung-mtk** [comment]
I didn't have this device, only test in my k2p.  Bugs only in my k2p. You can try it. Maybe, if i have time to push a commit to discuss.

**Comment by lukasz1992** [comment]
I will check if it is possible to backport **site_survey_for_channel** from other asuswrt GPL dump.

**Comment by ferhung-mtk** [comment]
RT-N800HP includes  enabled repeater, its source will be helpful, and it is almost the same with RT-AC85U. "rc/sysdeps/ralink/ralink.c" should use the one of RT-AC1200GU, it is the only one which leaked as .c file, **site_survey_for_channel** is in ralink.c.

**Comment by lukasz1992** [comment]
Thanks, I need to port 4 functions and dependencies for them.
As you suggested - I will use RT-AC1200GU as the base.

**Comment by ferhung-mtk** [comment]
By the way, how can you fix the losing 5G signal at rebooting?

**Comment by lukasz1992** [comment]
Open another ticket for it and provide details. Anyway source for 5GHz wireless driver is very old.

**Comment by lukasz1992** [comment]
I managed to compile it with REPEATER and PROXYSTA, in a near future I will post updated version.

**Comment by ferhung-mtk** [comment]
good, some nand's methods from your source, i port to xiaomi redmi ac2100, it works well.

**Comment by lukasz1992** [comment]
I have to go deeper in the changes you write on first post (%-4s%-33s%-20s%-23s%-9s%-7s%-7s%-3s), because they applies only to header - more important are next rows (and size match), will check them.

I am also going to use newer GPL (from RT-AC59U), with sources to Samba 3.6.x.

And actually I am going to revert these changes supporting dual-image on NAND. I will let single image similarly to OpenWRT. It is really painful for the rest of asus software parts - maintaning it is horrible.

I will also support more routers, as I just bought AC2100 router

**Comment by ferhung-mtk** [comment]
I commit my works in `https://gitee.com/ferhung-mtk/asuswrt_RM2100`, i am using source of RTN800HP.

**Comment by ferhung-mtk** [comment]
It's very glad to invite you to commit your fix for this repository.

**Comment by ferhung-mtk** [comment]
Repeater commit is just like the wds method having some changes. You can follow this commit: https://github.com/ferhung-mtk/asuswrt_k2p/commit/62b839f5c8a59802e5c58924313c187ce9f4dc7e

But it seems that the mt7603 driver need more tests.

**Comment by ferhung-mtk** [comment]
Add repeater support for RM2100,  now.

[https://gitee.com/ferhung-mtk/asuswrt_RM2100/commit/a9e337f6860f03cea4a976be84b58e482cf73a39](url)

**Comment by lukasz1992** [comment]
I did not test repeater, but it is included now.
