### ISSUE TITLE
SMB V2 Support

### ISSUE THREAD

**Issue by don-teka** [lukasz1992/asuswrt-xiaomi#33]
Please, would it be possible to include SMB V2 in the firmware? The router supports it, this has already been added to Padavan. SMB V1 is outdated and insecure.

**Comment by lukasz1992** [comment]
I decided to port 3.6 version as for IPQ40xx routers - I will push updated firmware in a near future.

**Comment by lukasz1992** [comment]
Done in f564aa4fe995a331a5eca5b11436577c5e8392cc ; soon will be released

**Comment by don-teka** [comment]
Thank you, I really appreciate your work with the firmware.

**Comment by lukasz1992** [comment]
Unfortunatelly it crashes constantly, this version does not work

**Comment by don-teka** [comment]
It really is a bad luck that it didn't work out, I pray that you will succeed in the implementation, Maybe a port from some other router is more stable.

**Comment by lukasz1992** [comment]
Constantly trying it.. But samba.3.6.x present in AX88U GPL does not compile

**Comment by adamnickster** [comment]
Hi I tried different Asus sources but now I'm using samba 3.6.x from padavan source(not 100% sure) everything works.

**Comment by lukasz1992** [comment]
@don-teka @adamnickster OK, managed to compile it. Fix 40d4ed74 in Makefile solved the issue. After testing I will publish image.

**Comment by don-teka** [comment]
Thanks for supporting SMB V2, I saw that you released a new version. But how do I get it to the router? since in the description it says it is not compatible with previous versions of the firmware.

**Comment by lukasz1992** [comment]
@don-teka Image needs to be flashed at offset 0x600000, as described here: https://github.com/lukasz1992/asuswrt-xiaomi
