### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by don-teka** [lukasz1992/asuswrt-xiaomi#34]
Sorry if I'm being inconvenient, but I don't feel comfortable updating the router, I think I have the breed installed on MIR3G, as I understand it, should I update it or am I wrong? and what you mean by "Please also backup settings and JFFS2 partition, before flashing". the settings I back up, but the partition you mention I don't know where to find it.

**Comment by lukasz1992** [comment]
If you have important data on JFFS, please archive it to temporary directory, download to PC, and after upgrade upload from PC, extract to JFFS partition. It is not necessary step.

If you have version 3.0.0.4_382_52072, you should not use AsusWRT to flash new image, Breed is OK. But I am not sure which partition is used by Breed by default.
If 0x60000, it will work out of the box.

You can backup flash, try load trx from Breed and see if it works.

**Comment by don-teka** [comment]
I was unable to install the Asuswrt, the second partition in the breed is 0x600000 but when trying to install in it the router always restarts in Breed and in the first partition that would be 0x200000 in Breed it restarts the router by changing the color of the leds but the asuswrt or the breed does not enter . I was forced to install the padvan on it so as not to lose the router.

**Comment by don-teka** [comment]
Well after 5 hours trying I finally gave up on the firmware, tried all possible options in the breed and nothing worked the router does not start or it always starts in the breed, there is something wrong with the firmware initialization. I don't know which method you used to install, but here I couldn't, I even updated Breed without success. Here I always use Breed so as not to take unnecessary risks, and both the previous version of Asuswrt and padavam install without problems, so the problem is probably the last compilation of Asuswrt.

**Comment by nicefile** [comment]
@don-teka I've had this once . It's because it's trying to boot from 2nd kernel (failover policy) Don't remember exact command but it's easy repair via serial console.

**Comment by don-teka** [comment]
I was looking forward to SMB v2, but I give up. I have no access to the hd but at least the router is working in the previous version. 5 hours of trial and error and nothing, I don't want to brik the router but without a doubt there must be a solution, Who knows in the near future things will improve.

**Comment by lukasz1992** [comment]
@don-teka release is working on my personal RT-MIR3G router (I use this image).
I have Breed, but did not try to flash image from it.

As described - image must be placed at 0x600000 offset - it is 2nd kernel partition (the first 4MB of image), and 1st rootfs (the rest of image). I am not author of Breed, you could possibly ask hackpascal.

If you flashed image correctly, and still does not boot, maybe this could be possible solution: https://forum.openwrt.org/t/xiaomi-3g-mir3g-breed-bootloader-configure-dual-boot-openwrt-pandorabox-padvan/22309/4
But anyway I did not need it.

If it still does not help I will write how to do flash from previous AsusWRT releases (for MIR3G).

**Comment by don-teka** [comment]
I honestly never had so much work to install a firmware, I got discouraged and honestly I don't know if I keep trying, I've tried all the ways, save the firmware on the 2 partitions, tried only on 0x200000, tried only on 0x600000, and nothing. If I record in 2 partitions the router does not start, if I record in 0x200000 and give the command to start in it, the router starts in Breed, if I record in 0x600000 and I give command to start in it, the router does not start. The previous firmware is written to 0x200000 and Breed is not given any command to start, I tried to do this and the router does not start with the latest firmware. I really appreciate his work, and I like the asuswrt because he has unique functions and full access to the app, I like it even more than Padavan, but all this work made me rethink my options. I am not an advanced user, but every day I learn a little more. This is the first firmware that I can't install.

**Comment by lukasz1992** [comment]
I am really sorry that you lost 5 hours; I actually lost much more on debugging AsusWRT internals.
I will provide you information how to flash from previous AsusWRT as I prepare commnds.

I can not tell which environment variables your Breed has set. On my router it works.
If you don't want to use this firmware, no problem - that's only your decision.
I do this work it in my spare time, without any payment - don't expect that everything just works.

**Comment by don-teka** [comment]
Please don't get me wrong, I give thanks to you, your efforts are memorable. I don't curse the 5 hours I lost, I feel sorry that it didn't work out, it was the first time this happened. I was just frustrated that I didn't succeed despite my efforts. I can't imagine what you spend to make this firmware available to us. Please don't give up. I should probably be to blame for the firmware not working, even though I don't know why. I did everything I knew and some things that friends with more experience indicated to me and nothing went right. I just got discouraged, the previous one is working more or less well, I still haven't completely given up, but I don't know if I try again or if I expect a new compilation.

**Comment by don-teka** [comment]
A million thanks, this method you posted allowed me to upload the firmware in 5 minutes, much simpler than anything else I would have tried. Again, I'm sorry if I missed you or your job, I was really discouraged and stressed, but now I feel relieved to have succeeded, this method you used is a thousand times simpler than any other of the breed. Thank you, continue your wonderful work with this firmware. I will do more tests, but it seems that everything is as I left after loading the backup settings.

**Comment by lukasz1992** [comment]
OK, thanks for this, I updated release notes, and will close the ticket.

Jun 8 18:12:19 usb: USB /dev/sda(ntfs) failed to mount At the first try!
Jun 8 18:12:19 usb: USB ntfs fs at /dev/sda mounted on /tmp/mnt/Main.
that is correct, I also had this warning.

Did you enable sharing with Samba? Does command on console:   ps | grep    show anything? Please open a new ticket for it.

SSH needs to be enabled manually, anyway dropbear does not work with SFTP protocol, try SCP.

**Comment by ferhung-mtk** [comment]
That is very strange i flash the firmware from my source, using breed, it booted well all the time. Including k2p and rm2100. RM2100 is using the breed of MIR3G, i think  it is not impossible to flash with breed. Check it to prove i am wrong.
[gitee.com/ferhung-mtk/asuswrt_RM2100](gitee.com/ferhung-mtk/asuswrt_RM2100)

**Comment by a86913179** [comment]
@lukasz1992 @don-teka 
FYI, If both kernel0 and kernel1 exist, then check the value of the environment variable `xiaomi.r3g.bootfw` in breed, if it exists and the value is 2, then start kernel1(0x600000), otherwise start kernel0 (0x200000)

So just add the environment variable `xiaomi.r3g.bootfw` in breed and set the value to 2, then flash the firmware to the second partition(kernel1) not the first partition(kernel0), done.
