### ISSUE TITLE
Support 160MHz for rm2100

### ISSUE THREAD

**Issue by ferhung-mtk** [lukasz1992/asuswrt-xiaomi#36]
[https://github.com/ferhung-mtk/asuswrt_RM2100/commit/7ef4ad2e1d819806fa669e7868dad86fc0eba8b1](https://github.com/ferhung-mtk/asuswrt_RM2100/commit/7ef4ad2e1d819806fa669e7868dad86fc0eba8b1)

**Comment by ferhung-mtk** [comment]
Update. 
https://github.com/ferhung-mtk/asuswrt_RM2100/commit/b2668f6f8f60f5dedbb21aaf1775422590342fd0

But still need to modify related files(ralink.c, ralink.h and web-ralink.c) in commit: https://github.com/ferhung-mtk/asuswrt_RM2100/commit/7ef4ad2e1d819806fa669e7868dad86fc0eba8b1

New method allows to disable 160MHz when some devices does not have 160MHz.

**Comment by lukasz1992** [comment]
Thanks, did you try to use 80+80? I am going to patch it after adding support for mt7615 (I try to find the reason, instead of https://github.com/ferhung-mtk/asuswrt_RM2100/commit/1917bf3623f026632ddf75d1a3a65cc0d35631ef renaming).

**Comment by ferhung-mtk** [comment]
I don't have a dual mt7615 device, I can't test 80+80.

**Comment by lukasz1992** [comment]
Fixed in d392b088
