### ISSUE TITLE
Fix slow rate of 2.4G by setting HT_BSSCoexistence=0 in rc/ralink.c.

### ISSUE THREAD

**Issue by ferhung-mtk** [lukasz1992/asuswrt-xiaomi#43]
HT_BSSCoexistence should be disabled, or the 2.4G  only has half rate(only recognize BW_20, but no BW_40).
It must be a bug of asuswrt or newer drivers(7603, 7615).

**Comment by lukasz1992** [comment]
Do you mean that router switches back to 20MHz even 40MHz was set? Did you confirm that after this change, it works on 40MHz?

It could be possibly a correct behaviour basing on https://www.smallnetbuilder.com/wireless/wireless-features/31743-bye-bye-40-mhz-mode-in-24-ghz-part-1 .

Anyway I can keep this setting enabled on 20/40MHz mode and force disabling it on 40MHz.

**Comment by ferhung-mtk** [comment]
No, bw_40 can't be recognized in auto mode (20/40MHz). Setting to 40MHz only, HT_BSSCoexistence will be disabled, no need to change anythings.
This fix only for auto mode.

**Comment by ferhung-mtk** [comment]
Setting HT_BSSCoexistence=0 means to disable DOT11N_DRAFT3. I know that is not a good idea. But you enable it, 40MHz will be disabled in auto bandwidth(20/40MHz).
By the way, padavan sets HT_BSSCoexistence=0 in all bandwidth.

**Comment by lukasz1992** [comment]
I think that any defaults should keep 20MHz channel. Some devices do not allow forcing 40MHz at all.

Are you sure that you these cases do not exist in your environment:
- other AP
- no client with 40mhz intolerant bit exists
- no “20/40 BSS Coexistence” management frame received from client

Anyway, please force 40MHz channel. In all other cases I think 40MHz in 2.4GHz is a bad idea.

**Comment by ferhung-mtk** [comment]
No, you didn't get it. Setting HT_BSSCoexistence=0 dose not mean to force 40MHz in all modes.
Both HT_EXTCHA=0 and HT_BSSCoexistence=0, it will force 40MHz at all. Only disable BBSCoexisttence, 20/40MHz all working.
Have a debug in your device, please! You will understand.

**Comment by lukasz1992** [comment]
Ok, trust you. Fix done in bbf08dae
