### ISSUE TITLE
Install custom scripts

### ISSUE THREAD

**Issue by mihei78** [lukasz1992/asuswrt-xiaomi#46]
Hello, are custom scripts supported for firmware blocking ads?

**Comment by lukasz1992** [comment]
Yes, introduced in d32dcc01
You have to create either:
a) custom executable script in /jffs directory (example: myscript.sh) and set nvram variable (example: `nvram set jffs2_exec=myscript.sh` for R4A or `nvram set ubifs_exec=myscript.sh` for other routers)
b) create executable script in /jffs/.asusrouter file

**Comment by akeilox** [comment]
@mihei78 which script are you using for blocking ads?

**Comment by mihei78** [comment]
I want to adapt the script from the Padawan firmware, I don’t have enough knowledge

#!/bin/sh

###Найден статичный hosts на флешке, копируем его в tmp
[ -f /opt/etc/hosts ] && logger "entware hosts file /opt/etc/hosts" && cp /opt/etc/hosts /tmp/hosts

modprobe ip_set
modprobe ip_set_hash_ip
modprobe ip_set_hash_net
modprobe ip_set_bitmap_ip
modprobe ip_set_list_set
modprobe xt_set
modprobe xt_HL

touch /tmp/hosts
sleep 90
###если отсутствует статичный файл, скачиваем его с интернета
[ ! -f /opt/etc/hosts ] &&
#logger "download adblok3.txt" && wget -qO- "http://i.dinis.ru/adblok3.txt" | grep -v '^#\|^[[:space:]]*$' | sed -e 's/^/0.0.0.0 /' >> /tmp/temp-hosts
###скачиваем обновляемый файл не зависимо есть ли что на флешке
#logger "download adlist.txt" && wget -qO- "http://adlock.dinis.ru/adlist.txt" | grep -v '^#\|^[[:space:]]*$' | sed -e 's/^/0.0.0.0 /' >> /tmp/temp-hosts
#logger "download Zero hosts file..." && wget -qO- "http://someonewhocares.org/hosts/zero/hosts" | awk -v r="0.0.0.0" '{sub(/^0.0.0.0/, r)} $0 ~ "^"r' >> /tmp/temp-hosts
logger "download MVPS hosts file..." && wget -qO- "http://winhelp2002.mvps.org/hosts.txt" | awk -v r="0.0.0.0" '{sub(/^0.0.0.0/, r)} $0 ~ "^"r' >> /tmp/temp-hosts
logger "download AdAway blocklist hosts file..." && wget -qO- "https://adaway.org/hosts.txt" |awk -v r="0.0.0.0" '{sub(/^127.0.0.1/, r)} $0 ~ "^"r' >> /tmp/temp-hosts
logger "download MalwareDomainList hosts file..." && wget -qO- "https://www.malwaredomainlist.com/hostslist/hosts.txt" |awk -v r="0.0.0.0" '{sub(/^127.0.0.1/, r)} $0 ~ "^"r' >> /tmp/temp-hosts
#logger "download hpHosts hosts file..." && wget -qO- "http://hosts-file.net/ad_servers.txt" |awk -v r="0.0.0.0" '{sub(/^127.0.0.1/, r)} $0 ~ "^"r' >> /tmp/temp-hosts
#logger "download Ad server hosts file..." && wget -qO- "http://pgl.yoyo.org/adservers/serverlist.php?hostformat=dnsmasq&showintro=0&mimetype=plaintext" |awk -v r="0.0.0.0" '{sub(/^127.0.0.1/, r)} $0 ~ "^"r' >> /tmp/temp-hosts
#logger "download DisableWinTracking hosts file..." && wget --no-check-certificate -qO- "https://gist.githubusercontent.com/10se1ucgo/fcb774d781a66ea9d31f/raw/f8ba0bca0f96390af1a613258c952b099942c3ee/ips+domains.txt" | grep -v '^#\|^[[:space:]]*$' | sed -e 's/^/0.0.0.0 /' >> /tmp/temp-hosts
logger "Updating /tmp/hosts file..." && cat /tmp/temp-hosts | sort -uk2 >> /tmp/hosts
rm /tmp/temp-hosts && logger "/tmp/hosts file has been successfully updated."

sed -i '1d' /tmp/hosts
sed -i '/localhost/d' /tmp/hosts
sed -i '/0.0.0.0 l-stat.livejournal.net/d' /tmp/hosts
sed -i '/0.0.0.0 clck.yandex./d' /tmp/hosts
sed -i '/0.0.0.0 adv.gpm-digital.com/d' /tmp/hosts
sed -i '/0.0.0.0 c.allegrostatic.pl/d' /tmp/hosts
sed -i '/0.0.0.0 s.click.aliexpress.com/d' /tmp/hosts
sed -i '/0.0.0.0 aliexpress.com/d' /tmp/hosts
sed -i '/0.0.0.0 best.aliexpress.com/d' /tmp/hosts
sed -i '/0.0.0.0 ad.admitad.com/d' /tmp/hosts
sed -i '/0.0.0.0 bit.ly/d' /tmp/hosts
sed -i '/0.0.0.0 torrent-tv.ru//d' /tmp/hosts
sed -i '$a0.0.0.0 octclck.xyz' /tmp/hosts
sed -i '$a0.0.0.0 z.cdn.ftd.agency' /tmp/hosts
sed -i '$a0.0.0.0 www.mgid.com' /tmp/hosts

killall -SIGHUP dnsmasq

**Comment by lukasz1992** [comment]
I see some differences:
- /jffs instead of /opt
- /tmp/etc/hosts instead of /tmp/hosts
- modprobe calls are not needed for this script

after that it should work
