### ISSUE TITLE
Support LED light on and off.

### ISSUE THREAD

**Issue by ferhung-mtk** [lukasz1992/asuswrt-xiaomi#48]
https://github.com/ferhung-mtk/asuswrt_RM2100/commit/7d23e96aae6e9b04ea5008daa4f7c8450bce51f5

If some devcies have a lan light, add it too.

By the way, if you use some commits from mine, it is glad that you give a mention (just like: @ferhung-mtk).

**Comment by lukasz1992** [comment]
I prefer to not import Merlin functionality. This also can be achived with custom scripts.

**Comment by ferhung-mtk** [comment]
It's not Merlin functionality. Lots of people just need it.

**Comment by NEOs007** [comment]
> I prefer to not import Merlin functionality. This also can be achived with custom scripts.

Then tell me how to disable the LEDs on your firmware, changing parameters such as:
nvram set led_pwr_gpio=4104
nvram set led_all_gpio=255
nvram set led_logo_gpio=255
nvram set led_wps_gpio=255
Don't lead to absolutely nothing.

**Comment by lukasz1992** [comment]
Use a custom script started on boot, and disable led within it, create /jffs/.asusrouter file, and put:
```
#!/bin/sh
sleep 5
led_ctrl 0 0
```

**Comment by NEOs007** [comment]
It really helped to turn off the front led, then tell me the led numbers on the back of the r3g router? 
Or better yet, add the power off button to the next version of your firmware, and the wireless power slider will also be useful.
Thank you for your work!

**Comment by lukasz1992** [comment]
Keep in mind that for each LAN/WAN port one led is controlled directly by switch, and the second (amber) by software - in AsusWRT they are disabled. Led numbers for R3G (v1) are: 13(WAN), 14(LAN1), 16(LAN2).

Ability to control switch leds in software is supported in AsusWRT but only when hardware does not support it - so not applicable in this case. If you want to control amber leds for network ports it can be done directly by **gpiow** command or with own implementation (calling ioctls on /dev/gpio0).

**Comment by NEOs007** [comment]
Very strange, I have R3G (v1) and 3.0.0.4_382_52113, but my led numbers are different, maybe they change from the firmware.
My WAN (amber) was disabled by the led_ctrl 6 0 command, but LAN1 (green) and LAN2 (green) are not disabled by numbers 13, 14, 16, until 30.
Is there a command where I can check my led numbers?
