### ISSUE TITLE
Network map in the web interface does not work

### ISSUE THREAD

**Issue by don-teka** [lukasz1992/asuswrt-xiaomi#49]
After updating to version 3.0.0.4.382_52113-b6d7d8f4 the network map on the web interface no longer works on MI3G. I didn't test router mode, but on access point mode when going to the network map on the webinterface, there is no listing of the number of connected hosts.
Clicking view lists shows a complete empty client list.

**Comment by lukasz1992** [comment]
I am not sure if it is supported on OEM firmware.
Hornestly I have never checker AP/Repeater modes.

Please show me output of `ps | grep networkmap`

**Comment by don-teka** [comment]
The network map works normally in AP mode. I always used the router in this mode, only in this last version that did not work. Here is the result of the commamd
Toor@RT-MIR3G:/tmp/home/root# ps | grep networkmap
379 Toor 6056 S networkmap --bootwait
954 Toor 1676 R grep networkmap

**Comment by lukasz1992** [comment]
Please write me `mount` output and `touch /jffs/something` output (if any), I want to check if something is wrong with /jffs partition

**Comment by don-teka** [comment]
Follow the output as requested. Mount command:
Toor@RT-MIR3G:/tmp/home/root# mount
rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
proc on /proc type proc (rw,relatime)
tmpfs on /tmp type tmpfs (rw,relatime)
devfs on /dev type tmpfs (rw,noatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600)
/dev/ubi0_0 on /jffs type ubifs (rw,noatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
usbfs on /proc/bus/usb type usbfs (rw,relatime)
/dev/sda on /tmp/mnt/Main type tntfs (rw,nodev,noatime,uid=0,gid=0,umask=00,nls=utf8,min_prealloc_size=64k,max_prealloc_size=488353788,readahead=4M,user_xattr,case_sensitive,fail_safe,hidden=show,dotfile=show,errors=continue,mft_zone_multiplier=1)

Command touch /jffs/something does not return anything

**Comment by don-teka** [comment]
Well, the network map is back to working out of nowhere. It was 2 days without working since I updated, restarted it 10 times, it was off for 4 hours due to lack of power, now the night just decided to work alone. I don't know what could have happened. I'm sorry I took your time.

**Comment by lukasz1992** [comment]
I wish you had logs we could check what was wrong.
My suspection is error with /jffs (problem with mounting, or errors lead to force read-only mode).

So you can confirm that access point mode works now?

**Comment by don-teka** [comment]
Yes it is working normally now, I confess that I am frustrated, I wanted to solve the problem and provide you with some data, but the system "fixed itself", I don't know how it happened but it has been working normally since last night.

**Comment by lukasz1992** [comment]
I hope it will stay working. Possibly asus could have some bugs.

If you know how much time I spent on working out asus code, finding drivers and so many times constantly failing...
