### ISSUE TITLE
MT7615 broken wireless log

### ISSUE THREAD

**Issue by fluffymadness** [lukasz1992/asuswrt-xiaomi#50]
The image for the redmi ac 2100 works fine so far.
However, under SystemLog->WirelessLog where the connected stations are shown
I only get clients listed for the 2.4ghz radio.
Right under the mac address for the 5ghz radio, nothing is listed at all.
The operation mode and channel is not displayed, and there is also no station list.

**Comment by lukasz1992** [comment]
Strange, but possible - as I have not tested mt7615 device. Could you copypaste it here?

**Comment by lukasz1992** [comment]
Please also put output of:
`nvram get wl_ifnames`

**Comment by fluffymadness** [comment]
```
admin@RT-RM2100:/tmp/home/root# nvram get wl_ifnames
ra0 rai0
```

```
MAC address	: 88:C3:97:42:0E:78
OP Mode		: AP
Channel		: 3

Stations List			   
----------------------------------------
MAC               PSM PhyMode BW  MCS SGI STBC Rate Connect Time
5C:CF:7F:07:2B:0C NO  OFDM    20M   7 NO  Yes   54M 03:26:14
D8:F1:5B:DE:E2:AF NO  OFDM    20M   7 NO  Yes   54M 01:52:04
C0:EE:FB:E1:1E:BC Yes OFDM    20M   5 NO  Yes   36M 00:00:44
3C:71:BF:31:8F:45 NO  OFDM    20M   7 NO  Yes   54M 01:21:09

MAC address	: 88:C3:97:42:0E:79
```

**Comment by fluffymadness** [comment]
Maybe ferhung-mtk also had that issue?
https://github.com/ferhung-mtk/asuswrt_RM2100/commit/a2372a5ace28cd83056c9d5cc504482aadd0c547

**Comment by lukasz1992** [comment]
Probably you are right, I will check if it is possible to fix it inside MTK driver

**Comment by lukasz1992** [comment]
Thanks for reporting, fixed in 43e59155

**Comment by lukasz1992** [comment]
I updated binaries, please redownload image and reflash it

**Comment by lukasz1992** [comment]
@fluffymadness could you check if MAC addresses for LAN, WAN, 2.4G and 5G WiFi are correct?

**Comment by fluffymadness** [comment]
@lukasz1992 
All three interfaces on my rm2100 are shown in the webinterface and have mac addresses that begin with 88:C3:97: 
The wifi macs are also correctly displayed in the wifi log.
Have the router running a few days now in AP Mode and didn't notice anything strange or unusual so far.
And thanks again for you effort to get it running on my rm2100 :)

**Comment by fluffymadness** [comment]
How do I check WAN MAC? Do I have to switch back to router mode?
When checking with ifconfig in AP mode
BR0, ETH2, VLAN1 have the same MAC address.

**Comment by lukasz1992** [comment]
That's correct.

What I wanted to ask is to compare the last byte (last 2 characters) of MAC address for:
eth2, eth3, ra0, rai0
interfaces - with ifconfig.

On my R3G router it is the following: eth2: 1B, eth3: 1C, ra0: 1D, rai0: 1E

Thanks
