### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by kissmorning** [lukasz1992/asuswrt-xiaomi#51]
i use Xiaomi MI R3G v1 router firmware :3.0.0.4.382_50210
I want to use some commands at the beginning of the router. but /jffs/.asusrouter doesn't work

is there any solution?

**Comment by kissmorning** [comment]
example this command
iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 16000:65000 -j DNAT --to-dest 192.168.3.5:16000-65000

**Comment by lukasz1992** [comment]
3.0.0.4.382_52112 is the first version that supports scripts.
Please upgrade to the newest release.

**Comment by kissmorning** [comment]
3.0.0.4.382_52112 and 52113 I'm having samba password problem in this version

**Comment by lukasz1992** [comment]
Old samba did not support SMBv2.

Please create a new ticket for Samba password problem, describe how to reproduce it - I will try to help.

**Comment by kissmorning** [comment]
I did update the version you mentioned, the script still doesn't work.
I created a file named .asusrouter in the jffs folder and wrote the command iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 15000: 65000 -j DNAT --to-dest 192.168.3.5:15000-65000. I restarted but it didn't work

**Comment by lukasz1992** [comment]
Please write this inside this script:
`#!/bin/bash
touch /tmp/script_started`

reboot, and check if /tmp/script_started is present.

This script runs very early, probably before networking setup is done.

**Comment by kissmorning** [comment]
result is negative Can you tell me what to do step by step?

**Comment by lukasz1992** [comment]
Could you run `chmod +x /jffs/.asusrouter` and test once again?

**Comment by kissmorning** [comment]
yess

**Comment by kissmorning** [comment]
do you want teamwiver connection?

**Comment by kissmorning** [comment]
id and password
1 700 012 948
3ipt11

**Comment by lukasz1992** [comment]
No, I do not have time now.

If it still does not work, I will investigate it and check on my router.

**Comment by kissmorning** [comment]
/jffs/.asusrouter inside
into the file you mentioned

#!/bin/bash
touch /tmp/script_started
iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 16000:65000 -j DNAT --to-dest 192.168.3.5:16000-65000

I wrote it right?

**Comment by lukasz1992** [comment]
Yes, if it is executable, /tmp/script_started should appear after a reboot

**Comment by kissmorning** [comment]
![2020-07-17_14-31-42](https://user-images.githubusercontent.com/68402414/87781973-53559f00-c83a-11ea-9153-45f82dd84017.png)
I restarted and no such file appears

**Comment by lukasz1992** [comment]
OK, I will investigate it

**Comment by lukasz1992** [comment]
Could you try to do this command:
`nvram set ubifs_exec=".asusrouter" ; nvram commit; reboot`

And check if file appears?

**Comment by lukasz1992** [comment]
Wait a moment before this test:

Replace in .asusrouter
`#!/bin/bash`
with
`#!/bin/sh`

**Comment by kissmorning** [comment]
it didn't work
![2020-07-17_16-35-45](https://user-images.githubusercontent.com/68402414/87791840-a71cb400-c84b-11ea-973b-814b0ba35692.png)

**Comment by lukasz1992** [comment]
Replace in .asusrouter
#!/bin/bash
with
#!/bin/sh

reboot router, and try again please

**Comment by kissmorning** [comment]
the problem continues

**Comment by kissmorning** [comment]
![2020-07-17_17-21-52](https://user-images.githubusercontent.com/68402414/87796458-0ed5fd80-c852-11ea-8d62-26dcd1a6b007.png)
![2020-07-17_17-21-14](https://user-images.githubusercontent.com/68402414/87796491-18f7fc00-c852-11ea-912c-b0e60c5c8b37.png)

**Comment by kissmorning** [comment]
Can you add a screen like this in the new version?
![2020-07-17_22-56-07](https://user-images.githubusercontent.com/68402414/87826035-df8ab500-c880-11ea-8b90-4701b9a575f7.png)

**Comment by lukasz1992** [comment]
I am not going to import functions from Padavan, but you can always fork my code.

I checked in my router, and problem does not occur - for me. I also did not need to create ubifs_exec variable, .asusrouter should be sufficent. Please show me `ls -la /jffs`

**Comment by lukasz1992** [comment]
Please also redownload and reflash the latest image.

After that, do commands:
`nvram unset ubifs_exec; nvram commit; chmod +x /jffs/.asusrouter; reboot`

**Comment by kissmorning** [comment]
problem persists. script not working
![2020-07-19_13-45-58](https://user-images.githubusercontent.com/68402414/87873057-ce4bc080-c9c6-11ea-87b6-8ca34832482c.png)

**Comment by kissmorning** [comment]
Contents of the .asusrouter file:
#!/bin/sh
touch /tmp/script_started
iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 16000:65000 -j DNAT --to-dest 192.168.3.5:16000-65000

**Comment by lukasz1992** [comment]
It means that script was run. Is the rule working now?

**Comment by kissmorning** [comment]
Sorry, it doesn't work

**Comment by lukasz1992** [comment]
Probably script runs before network initialization; you can now remove touch (as we now script works) and add:
`sleep 10` instead in this place, like this:
```
#!/bin/sh
sleep 10
iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 16000:65000 -j DNAT --to-dest 192.168.3.5:16000-65000
```

**Comment by kissmorning** [comment]
not working
![2020-07-19_16-40-40](https://user-images.githubusercontent.com/68402414/87876142-a9fbde00-c9de-11ea-8d40-c63140aee7fb.png)

**Comment by lukasz1992** [comment]
```
#!/bin/sh
touch /tmp/stage1
sleep 10
touch /tmp/stage2
iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 16000:65000 -j DNAT --to-dest 192.168.3.5:16000-65000
touch /tmp/stage3
```
save and reboot

**Comment by kissmorning** [comment]
not work
![2020-07-19_16-47-52](https://user-images.githubusercontent.com/68402414/87876268-af0d5d00-c9df-11ea-84fc-83d8188d930f.png)
![2020-07-19_16-48-48](https://user-images.githubusercontent.com/68402414/87876275-c1879680-c9df-11ea-892c-3378023a7931.png)

**Comment by lukasz1992** [comment]
New ideas:
- Increase sleep to 30
- Replace `iptables` with `/usr/sbin/iptables`

**Comment by kissmorning** [comment]
#!/bin/sh
touch /tmp/stage1
sleep 30
touch /tmp/stage2
/usr/sbin/iptables iptables -t nat -A PREROUTING -d 10.8.0.10 -p tcp --dport 16000:65000 -j DNAT --to-dest 192.168.3.5:16000-65000
touch /tmp/stage3

true?

**Comment by lukasz1992** [comment]
right

**Comment by kissmorning** [comment]
the problem persists. It did not work :(((

**Comment by lukasz1992** [comment]
No idea now.. I see the script runs on start. To be sure, please show me `iptables -t nat -L -v -n`

**Comment by kissmorning** [comment]
![2020-07-19_17-03-34](https://user-images.githubusercontent.com/68402414/87876602-d2390c00-c9e1-11ea-889b-df78a7ed69f8.png)

**Comment by kissmorning** [comment]
Thank you very much for your help. Currently, the script including samba and everything works smoothly

**Comment by lukasz1992** [comment]
Is it ok now? We have seen that script is working.
network script maybe needs more attention

**Comment by kissmorning** [comment]
everything works smoothly. I am thankful to you

**Comment by lukasz1992** [comment]
Good to know, thanks for testing.
