### ISSUE TITLE
samba password problem

### ISSUE THREAD

**Issue by kissmorning** [lukasz1992/asuswrt-xiaomi#52]
3.0.0.4_382_52113 after updating to this version, even though I entered the samba password correctly, it does not accept the password
![2020-07-17_14-37-38](https://user-images.githubusercontent.com/68402414/87782431-1fc74480-c83b-11ea-8b74-9257df0283b4.png)

**Comment by lukasz1992** [comment]
Actually it was already fixed in source code, but images were generated without fix. Thanks for reporting this!
I just updated release image. Please redownload latest release and reflash it, problem should have gone.

**Comment by kissmorning** [comment]
I tried everything, but after installing the software, the router does not receive ip. It works fine when I install version 3.0.0.4_382_50210. I'm using breed bootloader what could be the problem?

**Comment by lukasz1992** [comment]
Yes, flash mapping was changed. Please follow the instructions here:
https://github.com/lukasz1992/asuswrt-xiaomi/releases/tag/3.0.0.4_382_52107
You have to follow the instructions, you can flash directly 52113 release (you do not have to flash 52107)
