### ISSUE TITLE
[Q] How to reduce transmission power of 2.4ghz interface ?

### ISSUE THREAD

**Issue by fluffymadness** [lukasz1992/asuswrt-xiaomi#53]
Right now i have the problem that the router has too much
range in 2.4ghz band and i want to decrease it.

I have multiple 2.4ghz ap's, and
some of my distant iot nodes are constantly trying to connect to this router.
While they see the wifi, transmission packets can't reach the router because the radios of my nodes are probably not strong enough

At least I assume that's why I constantly get
```
Jul 18 13:40:21 kernel: BA - Send ADDBA request. StartSeq = 7e9,  FrameLen = 33. BufSize = 64
Jul 18 13:40:21 kernel: Del Sta:68:c6:3a:f9:7f:b8
Jul 18 13:40:21 kernel: ERROR!!! MlmeEnqueueForRecv(): un-recongnized mgmt->subtype=11, STA-68:c6:3a:f9:7f:b8
Jul 18 13:40:22 kernel: BA - Send ADDBA request. StartSeq = 483,  FrameLen = 33. BufSize = 64
```
in the syslog.

Are there any commandline commands that can display RSSI ?
Or is it possible to reduce transmission rate via cli for the 2.4ghz radio somehow.
Sadly in the ui there is no possibility to do so

**Comment by lukasz1992** [comment]
Theoretically there is a possibility to use this URL http://router.asus.com/update_clients.asp?_=timestamp to get json response with accurate results (rssi), but some headers are needed to work with it. This page uses IOCTL calls to get data directly from driver.

Please run:
`nvram set wl0_txpower=10; nvram commit; reboot` and see if it helps? If yes, I could implement switch in UI to control WiFi power

**Comment by fluffymadness** [comment]
the domain redirect somehow doesn't work for me.
Probably because I'm running both of my RM-AC1200 in ap mode.
Trying to call <ip-address>/update_clients.asp?_=timestamp kicks me right back to the login screen

**Comment by fluffymadness** [comment]
I'm not sure about my node too far away theory, because looking at the wireless log
the affected device shows 54M transmission rate. I think this should probably be a lot lower 
68:C6:3A:F9:7F:B8 NO  OFDM    20M   7 NO  Yes   54M 00:00:01

like
68:C6:3A:F9:75:17 NO  CCK     20M   0 NO  Yes    1M 02:30:37
68:C6:3A:F9:7C:9A NO  OFDM    20M   0 NO  Yes    6M 06:51:30

and these devices are not spamming any errors.
All are esp8266 devices (shelly)

**Comment by lukasz1992** [comment]
Actually you should not trust Wireless Log, as Asus definitions are really problematic here.
68:C6:3A:F9:7F:B8 NO OFDM 20M 7 NO Yes 54M 00:00:01 - probably means that actual rate is 72Mbps.

The problem is possibly here:
`ERROR!!! MlmeEnqueueForRecv(): un-recongnized mgmt->subtype=11, STA-68:c6:3a:f9:7f:b8` , possibly driver decides to disconnect station on unknown mgmt frame.

Do these devices work with other chipsets? Or did it work on previous versions of asuswrt?

**Comment by fluffymadness** [comment]
I just recently switched to the rm2100 for the shellys, so I don't really know if it had worked in a previous version.
All of these 68:... mac addresses are shelly 2.5 devices with an esp8266 inside.

**Comment by lukasz1992** [comment]
Even mt76 driver authors (linux experts) are not able to implement drivers correctly, so I (as a kernel beginner) am almost sure I am not able to fix problems (incompatibilities) with Mediatek drivers.

I can tell you how to enable all debugging on these drivers, how to change power, but do not even know if mt7603 chip is able to work with esp8266 devices. Did you try to disable 802.11n?

**Comment by fluffymadness** [comment]
Right now i adjusted the transmission power, rebooted.
And the same device spams the same errors. 
Then I set the 2.4ghz wifi to legacy
But it still started again:

Jul 18 14:19:18 kernel: Rcv Wcid(3) AddBAReq
Jul 18 14:19:18 kernel: Start Seq = 00000002
Jul 18 14:19:32 kernel: Del Sta:68:c6:3a:f9:7f:b8
Jul 18 14:19:36 kernel: ERROR!!! MlmeEnqueueForRecv(): un-recongnized mgmt->subtype=11, STA-68:c6:3a:f9:7f:b8

What is wrong with this esp8266 ^^"
All other esp8266 on my network work perfectly.

Anyways thanks for helping me to debug.
Wifi drivers seem to be really complex and diffcult stuff. I can't imagine how much hours and manpower went into developing such a chipset and  drivers for it.

Regarding transmission power...
nvram set wl0_txpower=10; nvram commit; reboot

how does the scale for this command work ?
Is it mw, dbm, percent?

What would I need to enter to return to the original transmission rate ?

**Comment by fluffymadness** [comment]
I guess that even the proprietary mt7603 driver is a bit unstable...

thats interesting:
n-only with the weaker transmission rate:
```
Jul 18 14:30:07 kernel: Del Sta:68:c6:3a:f9:7c:9a
Jul 18 14:30:07 kernel: Del Sta:68:c6:3a:f9:89:45
Jul 18 14:30:07 kernel: Del Sta:68:c6:3a:f9:7c:9c
Jul 18 14:30:07 kernel: Del Sta:68:c6:3a:f9:75:17
Jul 18 14:30:07 kernel: Del Sta:68:c6:3a:f9:84:0b
Jul 18 14:30:07 kernel: BA - Send ADDBA request. StartSeq = 30,  FrameLen = 33. BufSize = 64
Jul 18 14:30:08 kernel: sta port not secure, os should not send packets!!!
Jul 18 14:30:08 kernel: sta port not secure, os should not send packets!!!
```

**Comment by lukasz1992** [comment]
How does it scale? Good question... "Description: WLAN Radio Transmit Power setting in percentage" in MTK SoftAP programming guide does not tell what is it.

Probably mW, but we can just guess.

`nvram set wl0_txpower=100; nvram commit; reboot` will return value to default.

**Comment by lukasz1992** [comment]
Probably esp8266 wants to speak in all modes. Maybe 802.11b-only mode will solve problem?

I have 802.11n only mode enabled at my home, but know (even with Qualcomm chipsets) that some 802.11n-devices could not connect to 802.11n-only AP.

**Comment by fluffymadness** [comment]
Thanks. Btw, since I saw on the openwrt forum that you are trying to get proprietary drivers to run in openwrt.
While there is still not anything with proper cfg80211 support,

There seems to be a complete package for kernel 5.4 and mt7603, mt7612, mt7615 with mtwifi luci app
https://github.com/coolsnowwolf/lede/tree/master/package/lean/mt
Found it via this issue thread
https://github.com/openwrt/mt76/issues/419

**Comment by lukasz1992** [comment]
One question: Did you see that reducing power works? If yes, I could additional option for UI.

Yes, I tried to do it even with mt7603 driver. But I am not interested in custom luci plugins and scripts.
But I would be happy if cfg80211 support for official drivers could work - in that case nothing more than patched drivers would be needed for OpenWRT **native** support (no additional scripts, original hostapd/wpa_supplicant)

**Comment by fluffymadness** [comment]
Yes it seems to work. I went down from -65 to -73 dbm while doing link test with wifiman on an android phone.
When decreasing from 100 to 10

**Comment by lukasz1992** [comment]
OK, Thanks for tests
