### ISSUE TITLE
dont working download master

### ISSUE THREAD

**Issue by kissmorning** [lukasz1992/asuswrt-xiaomi#54]
hello thanks for everything.Thanks to this software, I started to love my xiaomi device more 👍 there is a minor problem. I get the error message as in the picture. what is the problem
![2020-07-30_20-01-19](https://user-images.githubusercontent.com/68402414/88952237-d39aec00-d29f-11ea-8bb0-118c6ff9add2.png)

**Comment by lukasz1992** [comment]
Hi @kissmorning , actually I never tested that feature. Is there anything in System log and kernel log?

**Comment by kissmorning** [comment]
Jul 30 20:00:05 rc_service: httpd 347:notify_rc start_apps_install downloadmaster sda5
Jul 30 20:00:33 rc_service: httpd 347:notify_rc email_info

**Comment by lukasz1992** [comment]
I will check it in my spare time, it is possible that I accidentally broke it in d32dcc014e477e0ec98420137a4ab6c1e202c884.

**Comment by mihei78** [comment]
@kissmorning Good afternoon, I apologize for writing in this thread, but I have not found how to send a private message to the user in GitHub. I need your help with scripts for asuswrt. I don't know your email address. Please contact me at mihei78@mail.ru

**Comment by lukasz1992** [comment]
Confirmed, I will update wget to fix it.

**Comment by lukasz1992** [comment]
Fixed in e7df22e5d27319650709069a9f055b4524a6e81a , will upload fixed build within 1 hour.

**Comment by lukasz1992** [comment]
Please redownload latest image and it should work now.

**Comment by kissmorning** [comment]
perfect working...thank you
