### ISSUE TITLE
Support for MT7620/MT7628 based xiaomi routers

### ISSUE THREAD

**Issue by shibajee** [lukasz1992/asuswrt-xiaomi#55]
Hi, tnx for ur good work. Not an actual issue but I don't know where to ask. Is this SDK has full support for other mediatek chipset like MT7620/MT7628 ? I mean i checked the code, it has CONFIG_RALINK_MT7620 etc. I can start porting for MI-3, 3C, 4C, NANO, MINI and sent some PR if I get a positive answer from u.

**Comment by lukasz1992** [comment]
Do not know about it. It possibly can support, but is not targeted to anything other than MT7621.
If you have the device and can send PR - you can do it, I will build image you could test.
