### ISSUE TITLE
Roaming Assistant is broken

### ISSUE THREAD

**Issue by fluffymadness** [lukasz1992/asuswrt-xiaomi#56]
When enabling the roaming assistant for a specific wifi interface (5ghz in my tests) and setting a threshold rssi value, it should
drop a wifi client when its rssi is under that value.
However nothing happens.
There is nothing shown in the logs either.
I tested this with a smartphone using wifiman and by setting an rssi value of -70dbm on the router...moving around with my smartphone I got to -90dbm and the router still didn't drop the client.
Killing and manually starting roaming assistant with "roamast" gives me the following:

admin@RT-RM2100:/tmp/home/root# killall roamast
admin@RT-RM2100:/tmp/home/root# roamast
rai0: Operation not supported

Hopefully this can be fixed somehow.

**Comment by lukasz1992** [comment]
Actually I have not tested Repeater. I will try to see what is inside roamast and what does it expect from driver. I can not anyway promise that it is possible to fix problem.

**Comment by lukasz1992** [comment]
Unfortunately it is a closed source implementation of ASUS_SUBCMD_GROAM subcmd in kernel driver.
Only thing I can do was to disable support for roaming assistant (7332be8e), sorry :-(

**Comment by fluffymadness** [comment]
@lukasz1992 np. thanks for trying.

**Comment by fluffymadness** [comment]
and for rssi (dbm) display in wireless log, in case you want to add it, see line 756 to 828
https://github.com/MerlinRdev/ac85p-merlin/blob/master/release/src/router/httpd/sysdeps/web-ralink.c

**Comment by lukasz1992** [comment]
Thanks for that @fluffymadness 
Could you show me screenshoot of previous release, with option to set it, and which nvram parameter is responsible for limit (or nvram dump)?

**Comment by fluffymadness** [comment]
![wirelesstab](https://user-images.githubusercontent.com/6042216/92246788-875a5180-eec6-11ea-8d54-61e6ecc77d3d.png)
Regarding roaming...I have no idea with the nvram parameters. I think the roaming assistant option normally would use the ASUS_SUBCMD_GROAM in the mtk driver, as you've explained (which we sadly don't have in the driver source code)

This commands should be able to control the driver directly for each wifi interface (as an alternative)
https://linux.die.net/man/8/iwpriv
```
iwpriv ra0 set KickStaRssiLow=-85 (Client rssi when to kick)
iwpriv ra0 set AssocReqRssiThres=-80 (If client rssi is worse than that connection is denied)
iwpriv rai0 set KickStaRssiLow=-85
iwpriv rai0 set AssocReqRssiThres=-80
```

Padavan had it implemented in their ui with this commit
https://github.com/hanwckf/rt-n56u/commit/5142b0e0203932976a1c102e86c9c3eeed11cc11

**Comment by fluffymadness** [comment]
I think this parameter AssocReqRssiThres=-80 is important that, when a client gets kicked at -85 it would be constantly trying to reconnect and would be kicked again. 
So this way, the client would only be able to reconnect if the rssi is >-80dbm

**Comment by lukasz1992** [comment]
OK, understood and can set this a static value. But please describe me how does "roaming assistant" look like in the User Interface?
My only device is working as main AP, can not test it at this moment.

**Comment by fluffymadness** [comment]
On the asus interface there is nothing more than the one value from my screenshot above that can be set.
It is just the threshold value when a client should be kicked from the wifi.
Asus calls it "roaming assistant" but it is nothing advanced like mesh steering(802.11k, 802.11v).

Its basically acts as a simple bouncer that just drops the client off the network when it goes under the rssi threshold. The idea behind it is just when you have e.g two access points e.g one ground floor and one at the first floor.:

You are at the ground floor with your phone and have an rssi of e.g -45dbm then you move up to the first floor.
Normally the phone would stick to the ap even if you have already an rssi of -90dbm on the first floor.
If you've enabled the roaming assistant, it will kick a client when the rssi goes below a certain value. E.g if you set KickStaRssiLow=-80 the router will kick the client when the signal goes under -80dbm.
This way the client should pick up the access point on the first floor faster.

**Comment by fluffymadness** [comment]
Basically these two values need to be fine tuned depending on the environment of the user, where the different access points are placed.

**Comment by lukasz1992** [comment]
I will check the logic of prebuilt rc module and think about reimplementation. I will keep this open

**Comment by lukasz1992** [comment]
> The iwpriv command however has two values. Basically these two values need to be fine tuned depending on the environment of the user, where the different access points are placed.
> 
> iwpriv ra0 set KickStaRssiLow=-85 (RSSI when the client should be kicked from the router)
> iwpriv ra0 set AssocReqRssiThres=-80 (If client rssi is worse than that connection is denied, e.g if client has now -83 after he was kicked, he won't be able to reconnect until he has an rssi of -80 or above again)
> And the client will automatically try to reconnect because he doesn't know why he was kicked in the first place)

Could you try these commands and check it they helps?
I mean please try these commands and check if these really provide roaming assistant functionality
