### ISSUE TITLE
Wired lan isn't working rm2100

### ISSUE THREAD

**Issue by bturnni** [lukasz1992/asuswrt-xiaomi#57]
Wired connection detected in the log that up when connects, but not working, while wifi does.

**Comment by lukasz1992** [comment]
Could you tell me how LED looks like? I mean what amber/green/yellow leds are there in back of the router for each port?

**Comment by bturnni** [comment]
I already have switched to other firmware, can't remember the LEDs. There isn't not led on each port. I followed https://m.youtube.com/watch?v=I5voa8q4ol8 so pretty sure you can see the LEDs there. Thanks.

**Comment by lukasz1992** [comment]
Thanks for this report, I will check what is wrong with LAN ports.

**Comment by lukasz1992** [comment]
Fixed in 78822617 , will update release in 1 hour
