### ISSUE TITLE
can i flash rm2100 with breed? 

### ISSUE THREAD

**Issue by jinglei207** [lukasz1992/asuswrt-xiaomi#58]
can i flash rm2100 with breed?

**Comment by lukasz1992** [comment]
If you can not find breed for this device I would not recommend it - I would expect switch(lan/wan) misconfiguration, reset button not working and possibly images not bootable. I tested rm2100 only with oem bootloader.

Please ask hackpascal about it.

**Comment by jinglei207** [comment]
I have flashed the breed for 3g and it doesn't work with your firmware. I saw from right.com.cn that bp-boot for ac2100 works.

**Comment by lukasz1992** [comment]
Image needs to be flashed at 0x600000 and kernel0 at 0x200000 should be erased. Is the location correct?
