### ISSUE TITLE
R2100 (black) BOOT Failed

### ISSUE THREAD

**Issue by cym422948** [lukasz1992/asuswrt-xiaomi#59]
virsion:RT-R2100_3.0.0.4_382_52113-b6d7d8f4.trx
breed(bootloader) set autoboot from 0x600000
Led no light, Can't boot system(Dhcp stop working?)
I wii keep trying

**Comment by cym422948** [comment]
Solved [https://github.com/lukasz1992/asuswrt-xiaomi/issues/47#](url)
First:Flash this firmware   [https://github.com/ferhung-mtk/rm2100-merlin](url)
Then:Use WINSCP upload lukasz1992 firmware to /tmp
Finally:run following commands
dd if=RM2100.trx bs=1048576 count=4 of=kernel
dd if=RM2100.trx bs=1048576 skip=4 of=root
mtd-erase -d linux
mtd-write -i kernel -d linux2
mtd-write -i root -d RootFS
After these commands  reboot into breed
flag_try_sys1_failed flag to 1
NOW IT'S Worked

**Comment by lukasz1992** [comment]
I am not sure if breed uploads image to 0x600000 or 0x200000. 0x600000 must be used.
