### ISSUE TITLE
Traffic Analyzer

### ISSUE THREAD

**Issue by phntms** [lukasz1992/asuswrt-xiaomi#60]
@ RT-MIR3G_3.0.0.4_382_52288-geac6f28.trx 
Traffic Analyzer does not analyze the applications anymore. There is only one app "General" for the whole traffic.

**Comment by lukasz1992** [comment]
Yes, I confirm the bug and will look for solution

**Comment by lukasz1992** [comment]
Should be fixed in c1694994. I am currently checking it and will publish images if it really works correctly
