### ISSUE TITLE
Problem with the samba version

### ISSUE THREAD

**Issue by don-teka** [lukasz1992/asuswrt-xiaomi#61]
I just updated my MI R3G to the latest version and I'm having problems with samba, it seems to have returned to smb v1 and I'm not being able to access it through SMBV2. So everything on my internal network stopped working, could you see what happened?

**Comment by lukasz1992** [comment]
3.0.0.4.382.52289? Will check it

**Comment by don-teka** [comment]
Yes version installed is 3.0.0.4.382.52289, please verify. Thanks.

**Comment by lukasz1992** [comment]
Fixed in 52095dfd, please redownload image and check if it is ok now.

**Comment by don-teka** [comment]
Thank you very much, it's working now.
