### ISSUE TITLE
可以增加软件中心吗

### ISSUE THREAD

**Issue by fengyu6251** [lukasz1992/asuswrt-xiaomi#64]
现在的功能有点少，但是很稳定，希望可以增加软件中心安装插件

**Comment by lukasz1992** [comment]
Hi, I am basing only on official AsusWRT. What more is needed? Can you write in english?

**Comment by happy201807** [comment]
Is it possible to open the jffs partition to install some useful plug-ins?

**Comment by lukasz1992** [comment]
Sure, jffs partition should be already (automatically) mounted.
If is not, please post here `dmesg` output

**Comment by happy201807** [comment]
How to compile .bin that can be run in jffs? How to use the toolchain environment? Can you provide complete steps? thank you

**Comment by lukasz1992** [comment]
Download RT-AC85U GPL and there is toolchain inside - like here.

You can also use OpenWRT 15.05.1 SDK https://archive.openwrt.org/chaos_calmer/15.05.1/ramips/mt7621/OpenWrt-SDK-15.05.1-ramips-mt7621_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
