### ISSUE TITLE
How to install for OpenWRT users MIR3g v1 ? 

### ISSUE THREAD

**Issue by xcom169** [lukasz1992/asuswrt-xiaomi#65]
Hello!

How to install for OpenWRT users MIR3g v1 ?  We don't have kernel0. 

root@OpenWrt:/tmp# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00080000 00020000 "Bootloader"
mtd1: 00040000 00020000 "Config"
mtd2: 00040000 00020000 "Bdata"
mtd3: 00040000 00020000 "Factory"
mtd4: 00040000 00020000 "crash"
mtd5: 00040000 00020000 "crash_syslog"
mtd6: 00040000 00020000 "reserved0"
mtd7: 00400000 00020000 "kernel_stock"
mtd8: 00400000 00020000 "kernel"
mtd9: 07580000 00020000 "ubi"

**Comment by lukasz1992** [comment]
Please check this https://github.com/lukasz1992/asuswrt-xiaomi/wiki/Installation and tell if it was sufficient.

**Comment by vgmz95** [comment]
Hi, I tried installing the firmware following the instruction on the wiki (failsafe), but I got the following error message: "Couldn't open image file: data!", I tried changing data to bdata but I got the same message. I'm using OpenWRT in the lastest snapshot.

**Comment by lukasz1992** [comment]
Instruction was just fixed, please check wiki again

**Comment by vgmz95** [comment]
Thanks, it worked. Just in case, how do I go back to openwrt/stock?

**Comment by xcom169** [comment]
Hello All!

Is it possible to install it from Breed ? 
If my Wifi5G doesn't support WPA3, can it be calculated on the CPU instead?

**Comment by lukasz1992** [comment]
Yes, it can be calculated - some guys ported WPA3 to MT76x2 driver, but don't share the source code.
Without updated driver no support is possible for WPA3.

Breed - Yes, it is probably possible, but I do not support it.

Returning back to OEM is more complicated - as kernel partition size is not constant.
I need to have all firmwares to write instruction.
