### ISSUE TITLE
noob cant flash. pls help

### ISSUE THREAD

**Issue by GA0000** [lukasz1992/asuswrt-xiaomi#66]
hi mate, i have tested some firmware. iam interested in asuswrt for yiaomi r3g. so i have tested it to flash but get error directly.

What i have done:
Xiaomi Stock firmware 2.25.122
SSH file flashed

transfer the 3.0.0.4_382_52289 via scp to /tmp

insert youre commands in ssh (putty)

root@XiaoQiang:~# nvram set flag_try_sys1_failed=1
root@XiaoQiang:~# nvram commit
root@XiaoQiang:~# mtd erase linux
Could not open mtd device: linux
Could not open mtd device: linux
root@XiaoQiang:~# dd if=/tmp/firmware.trx of=data bs=4194304 count=1
dd: can't open 'data': Read-only file system
root@XiaoQiang:~# mtd write data linux2
Couldn't open image file: data!

problem began with erase linux, than also cant open data. i really want asuswrt, pls help.

**Comment by lukasz1992** [comment]
I updated the instructions - please run `cd /tmp` before other commands
