### ISSUE TITLE
Flashing R2100: Could not open mtd device

### ISSUE THREAD

**Issue by marcodlima** [lukasz1992/asuswrt-xiaomi#68]
I'm trying to flash from original firmware Xiaomi R2100, i upload the trx file to /tmp but it gives me error on command "mid erase linux"

root@XiaoQiang:~# cd /tmp/
root@XiaoQiang:/tmp# nvram set flag_try_sys1_failed=1
root@XiaoQiang:/tmp# nvram commit
root@XiaoQiang:/tmp# mtd erase linux
Could not open mtd device: linux
Could not open mtd device: linux

Can you help?

**Comment by lukasz1992** [comment]
can you provide me output of
`cat /proc/mtd`

**Comment by marcodlima** [comment]
Here it is, and firmware version is 2.0.743

root@XiaoQiang:/tmp# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 07f80000 00020000 "ALL"
mtd1: 00080000 00020000 "Bootloader"
mtd2: 00040000 00020000 "Config"
mtd3: 00040000 00020000 "Bdata"
mtd4: 00040000 00020000 "Factory"
mtd5: 00040000 00020000 "crash"
mtd6: 00040000 00020000 "crash_syslog"
mtd7: 00040000 00020000 "cfg_bak"
mtd8: 00400000 00020000 "kernel0"
mtd9: 00400000 00020000 "kernel1"
mtd10: 01a00000 00020000 "rootfs0"
mtd11: 01a00000 00020000 "rootfs1"
mtd12: 02600000 00020000 "overlay"
mtd13: 01b80000 00020000 "obr"
mtd14: 00c1c000 0001f000 "ubi_rootfs"
mtd15: 021e8000 0001f000 "data"

**Comment by lukasz1992** [comment]
I updated the wiki, check updated instruction and tell if it works now.

**Comment by marcodlima** [comment]
That worked great!

Thanks a lot!
