### ISSUE TITLE
BW Redmi AC 2100

### ISSUE THREAD

**Issue by CessXP** [lukasz1992/asuswrt-xiaomi#69]
I don't know if there is a bug in bw selection, almost all my devices are in 20M even in front of the router when I pretty sure that my devices are capables for 80M, and the download is locked in 263Mbps, I have a 320Mbps connection from my ISP

PSM PhyMode BW  MCS SGI STBC Rate Connect Time
NO  OFDM    40M   7 NO  Yes   54M 00:56:05
NO  HTMIX   20M   7 Yes Yes   72M 00:01:09 
NO  HTMIX   20M  73 Yes Yes  263M 07:21:56

**Comment by CessXP** [comment]
![Screenshot_20201129-104826823](https://user-images.githubusercontent.com/31802781/100548156-76547e80-3230-11eb-9bda-88ca1a1e312b.jpg)

**Comment by lukasz1992** [comment]
You can not rely on this page - it does not work correctly for OEM Mediatek drivers without proprietary Asus patches.

Check how your connection on device looks like (signal strength, reported speed),
Let me know what is the channel and show your settings for WiFi (both Professional and Main pages).
Please also attach system log.

**Comment by lukasz1992** [comment]
Please also specify chipset of client device that you are testing.

**Comment by CessXP** [comment]
> Please also specify chipset of client device that you are testing.

I tested with two devices, one laptop with Atheros QCA9377 full signal, 866/433 link, one meter away from the router and a Mi A3 with SD 665, one meter away from router, full signal, 390/325 link, max speed in both is 260 mbps.
![Screenshot_3](https://user-images.githubusercontent.com/31802781/100554715-33100500-325c-11eb-82fc-d388ec1bba29.png)
![Screenshot_4](https://user-images.githubusercontent.com/31802781/100554716-33a89b80-325c-11eb-8f09-64a881c041f7.png)




Used channel is 40

**Comment by CessXP** [comment]
[syslog.txt](https://github.com/lukasz1992/asuswrt-xiaomi/files/5612914/syslog.txt)

**Comment by lukasz1992** [comment]
This would be difficult tome, because I could do nothing about driver implementation. Anyway I thing some settings could be tweaked:
- Set Wireless Mode to N/AC mixed
- Disable TX Bursting
- Optionally do a manual scan and select the best channel yourself

I consider both devices are 1x1 802.11ac so theoretical speed could not exceed 433Mbps. I have managed to get speeds like 320mbps in such conditions. If you want to work with that, please provide me output:
`cat /etc/Wireless/iNIC/iNIC_ap.dat` , we could possibly tweak some settings, but I can not promise if it helps.

**Comment by CessXP** [comment]
I tried the config, but didnt worked

#The word of "Default" must not be removed
Default
CountryRegion=0
CountryRegionABand=0
CountryCode=US
BssidNum=1
SSID1=ChocoWiFi5G
SSID2=
SSID3=
SSID4=
SSID5=
SSID6=
SSID7=
SSID8=
WirelessMode=15
FixedTxMode=
TxRate=0
Channel=0
BeaconPeriod=100
DtimPeriod=1
TxPower=100
DisableOLBC=0
BGProtection=0
TxAntenna=
RxAntenna=
TxPreamble=1
RTSThreshold=2347
FragThreshold=2346
TxBurst=1
PktAggregate=1
FreqDelta=0
TurboRate=0
WmmCapable=1
APAifsn=3;7;1;1
APCwmin=4;4;3;2
APCwmax=6;10;4;3
APTxop=0;0;94;47
APACM=0;0;0;0
BSSAifsn=3;7;2;2
BSSCwmin=4;4;3;2
BSSCwmax=10;10;4;3
BSSTxop=0;0;94;47
BSSACM=0;0;0;0
AckPolicy=0;0;0;0
APSDCapable=1
DLSCapable=0
NoForwarding=0
NoForwardingBTNBSSID=0
HideSSID=0
ShortSlot=1
AutoChannelSelect=1
AutoChannelSkipList=165;132;136;116;140;
IEEE8021X=0
IEEE80211H=1
DfsEnable=1
RDRegion=FCC
CarrierDetect=0
PreAntSwitch=
PhyRateLimit=0
DebugFlags=0
FineAGC=0
StreamMode=3
StreamModeMac0=
StreamModeMac1=
StreamModeMac2=
StreamModeMac3=
StationKeepAlive=0
CSPeriod=10
DfsLowerLimit=0
DfsUpperLimit=0
DfsIndoor=1
DFSParamFromConfig=0
FCCParamCh0=
FCCParamCh1=
FCCParamCh2=
FCCParamCh3=
CEParamCh0=
CEParamCh1=
CEParamCh2=
CEParamCh3=
JAPParamCh0=
JAPParamCh1=
JAPParamCh2=
JAPParamCh3=
JAPW53ParamCh0=
JAPW53ParamCh1=
JAPW53ParamCh2=
JAPW53ParamCh3=
FixDfsLimit=0
LongPulseRadarTh=0
AvgRssiReq=0
DFS_R66=0
BlockCh=
GreenAP=0
PreAuth=0
AuthMode=WPA2PSK
EncrypType=AES
WapiPsk1=
WapiPsk2=
WapiPsk3=
WapiPsk4=
WapiPsk5=
WapiPsk6=
WapiPsk7=
WapiPsk8=
WapiPskType=
Wapiifname=
WapiAsCertPath=
WapiUserCertPath=
WapiAsIpAddr=
WapiAsPort=
RekeyMethod=TIME
RekeyInterval=3600
PMKCachePeriod=60
MeshAutoLink=0
MeshAuthMode=
MeshEncrypType=
MeshDefaultkey=0
MeshWEPKEY=
MeshWPAKEY=
MeshId=
WPAPSK1=Chocolate90
WPAPSK2=
WPAPSK3=
WPAPSK4=
WPAPSK5=
WPAPSK6=
WPAPSK7=
WPAPSK8=
DefaultKeyID=1
Key1Type=0
Key1Str1=
Key1Str2=
Key1Str3=
Key1Str4=
Key1Str5=
Key1Str6=
Key1Str7=
Key1Str8=
Key2Type=0
Key2Str1=
Key2Str2=
Key2Str3=
Key2Str4=
Key2Str5=
Key2Str6=
Key2Str7=
Key2Str8=
Key3Type=0
Key3Str1=
Key3Str2=
Key3Str3=
Key3Str4=
Key3Str5=
Key3Str6=
Key3Str7=
Key3Str8=
Key4Type=0
Key4Str1=
Key4Str2=
Key4Str3=
Key4Str4=
Key4Str5=
Key4Str6=
Key4Str7=
Key4Str8=
HSCounter=0
HT_HTC=1
HT_RDG=1
HT_LinkAdapt=0
HT_OpMode=0
HT_MpduDensity=5
HT_EXTCHA=0
HT_BW=1
HT_BSSCoexistence=0
HT_AutoBA=1
HT_BADecline=0
HT_AMSDU=0
HT_BAWinSize=64
HT_GI=1
VHT_SGI=1
VHT_STBC=1
VHT_LDPC=1
HT_STBC=1
HT_MCS=33
HT_TxStream=4
HT_RxStream=4
HT_PROTECT=1
HT_DisallowTKIP=1
VHT_BW=1
VHT_DisallowNonVHT=0
ITxBfEn=0
ETxBfEnCond=1
MUTxRxEnable=1
ETxBfIncapable=1
WscConfMode=0
WscConfStatus=2
WscVendorPinCode=12345670
AccessPolicy0=0
AccessPolicy1=0
AccessPolicy2=0
AccessPolicy3=0
AccessControlList0=
RADIUS_Key1=
RADIUS_Key2=
RADIUS_Key3=
RADIUS_Key4=
RADIUS_Server=
RADIUS_Port=
RADIUS_Acct_Server=
RADIUS_Acct_Port=1813
RADIUS_Acct_Key=
own_ip_addr=
Ethifname=
EAPifname=
PreAuthifname=
session_timeout_interval=0
idle_timeout_interval=0
WiFiTest=0
TGnWifiTest=0
ApCliEnable=0
ApCliSsid=
ApCliBssid=
ApCliAuthMode=
ApCliEncrypType=
ApCliWPAPSK=
ApCliDefaultKeyID=0
ApCliKey1Type=0
ApCliKey1Str=
ApCliKey2Type=0
ApCliKey2Str=
ApCliKey3Type=0
ApCliKey3Str=
ApCliKey4Type=0
ApCliKey4Str=
MACRepeaterEn=0
MACRepeaterOuiMode=0
RadioOn=1
SSID=
WPAPSK=
Key1Str=
Key2Str=
Key3Str=
Key4Str=
IgmpSnEnable=0
McastPhyMode=0
McastMcs=0
WscManufacturer=ASUSTeK Computer Inc.
WscModelName=WPS Router (5G)
WscDeviceName=ASUS WPS Router (5G)
WscModelNumber=RT-RM2100
WscSerialNumber=00000000
WscV2Support=0
MaxStaNum=0;
EfuseBufferMode=0
E2pAccessMode=2
SKUenable=1
PMFMFPC=0
PMFMFPR=0
PMFSHA256=0

**Comment by CessXP** [comment]
And don't problem, I understand, your work is great :)

**Comment by lukasz1992** [comment]
Please try the following:

1) 
nvram set wl1_txbf_en=1
nvram commit
reboot

And check if anything was improved

2)
After reboot:
sed 's/TxBurst=1/TxBurst=0/g' -i /etc/Wireless/iNIC/iNIC_ap.dat
ifconfig rai0 down && ifconfig rai0 up

You could try variants: 1) only, both 1) and 2)

**Comment by CessXP** [comment]
This one worked 

nvram set wl1_txbf_en=1
nvram commit
reboot

**Comment by CessXP** [comment]
I think his a little better without this, the speed is faster with this too
sed 's/TxBurst=1/TxBurst=0/g' -i /etc/Wireless/iNIC/iNIC_ap.dat
ifconfig rai0 down && ifconfig rai0 up

**Comment by lukasz1992** [comment]
To sum up:

- applying setting for TxBurst helped
- txbf patch was making things worse

Did I understand correctly?

**Comment by CessXP** [comment]
> To sum up:
> 
> * applying setting for TxBurst helped
> * txbf patch was making things worse
> 
> Did I understand correctly?

Yes and a little worse

**Comment by CessXP** [comment]
I just made a clean flash coming from stock firmware and everything is working ok, I'm getting 300 mbps of download with 5Ghz .-.

**Comment by lukasz1992** [comment]
Will include a patch 97795a06 in a new release, I will close this ticket
