### ISSUE TITLE
Back to Stock Xiaomi

### ISSUE THREAD

**Issue by GA0000** [lukasz1992/asuswrt-xiaomi#70]
Hello together,

i flashed all. works very nice. its perfect original wrt. But now i flashed 4 devices and need to go back with 1 device again to stock firmware. stock i need go back is version miwifi_r3g_firmware_12f97_2.25.124.bin

link: 
https://www.dropbox.com/s/lclhuuxucxv63nl/miwifi_r3g_firmware_12f97_2.25.124.bin?dl=1

please help mate

**Comment by lukasz1992** [comment]
OK, I can not guarantee any success - but will do my best to help reverting to Stock;
I will not take responsibility for any damages.

If is it OK for you, please:
1. 
Copy oem firmware image to /tmp/ and run those commands:
```
dd if=miwifi_r3g_firmware_12f97_2.25.124.bin bs=740 skip=1 | dd bs=3498324 count=1 of=/tmp/kernel-oem
mtd write -i /tmp/kernel-oem -d linux
reboot
```
According to OpenWRT docs, it will boot stock kernel image which is able to flash firmware correctly:

> Wait with system red light slowly blinking for a FAT formatted usb stick with a recovery image to be inserted. Press and hold the reset button for around 1 second. Status LED will turn yellow during recovery and blue when recovery complete.
