### ISSUE TITLE
AsusWRT on R2100 (black cylinder) with stock Xiaomi rom

### ISSUE THREAD

**Issue by p4c0ga** [lukasz1992/asuswrt-xiaomi#71]
Could directly put the RT-R2100_3.0.0.4_382_52289-geac6f28.trx version since the Xioami stock rom?
![Captura](https://user-images.githubusercontent.com/63509535/102390767-210cc100-3fd5-11eb-819f-ac236c48984b.PNG)

**Comment by lukasz1992** [comment]
This would not work this way - you need console access. Then follow the instructions:
https://github.com/lukasz1992/asuswrt-xiaomi/wiki/Installation
