### ISSUE TITLE
AsusWRT on AC2100 (black cylinder)

### ISSUE THREAD

**Issue by p4c0ga** [lukasz1992/asuswrt-xiaomi#72]
![Captura](https://user-images.githubusercontent.com/63509535/102394674-654e9000-3fda-11eb-8365-dce89c93d735.PNG)

Can I load the released RT-R2100_3.0.0.4_382_52289-geac6f28.trx directly since the upgrade button of Xiaomi stock rom ?

Thanks in advance

**Comment by lukasz1992** [comment]
This would not work this way - you need shell access. Then follow the instructions:
https://github.com/lukasz1992/asuswrt-xiaomi/wiki/Installation
