### ISSUE TITLE
Asuswrt on r3g v1

### ISSUE THREAD

**Issue by Dzafo** [lukasz1992/asuswrt-xiaomi#73]
Hi Lukasz,

i tryed your asuswrt on my r3g v1, but my router doesnt boot and the led doenst light up (sry for my bad english). 
![B36FE36C-50E6-43CD-84C5-CCC8FD398986](https://user-images.githubusercontent.com/77195291/104090954-75c0f600-527a-11eb-81ad-9707b685a6e1.png)
Have you some idea what i doo wrong ? Thank you

**Comment by Dzafo** [comment]
Ok the router only two timed blink and booted to breed. When i tried flash your fw over breed the router only reboot and the blue light doenst light up ...

**Comment by Dzafo** [comment]
Ok sry my fault, now its working :)

**Comment by Dzafo** [comment]
I have second question, its possible to turn on jffs ? I try install entware, thank you

**Comment by Dzafo** [comment]
![Uploading C7BD896B-A9FA-40B3-99E7-E7FFFDFB739C.png…]()

**Comment by Dzafo** [comment]
![4056BBF8-2003-461E-99C1-9677C78F2E4E](https://user-images.githubusercontent.com/77195291/104104856-df58f880-52aa-11eb-97a7-13d76838d6eb.png)

**Comment by lukasz1992** [comment]
I will not take responsibility for any failures with custom scripts. Anyway you could ignore the check by running this command: `mkdir /jffs/scripts`
