### ISSUE TITLE
Noob building

### ISSUE THREAD

**Issue by CessXP** [lukasz1992/asuswrt-xiaomi#75]
INSTALL include/asm/rt2880 (1 file)
  INSTALL include/asm (37 files)
make[4]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010/linux/linux-3.10.14.x'
make -C /home/cesar/asuswrt-xiaomi/release/src-ra-5010/linux/linux-3.10.14.x prepare scripts
make[4]: se entra en el directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010/linux/linux-3.10.14.x'
/bin/sh: 1: mipsel-uclibc-gcc: not found
/bin/sh: 1: mipsel-uclibc-gcc: not found
/bin/sh: 1: mipsel-uclibc-gcc: not found
/bin/sh: 1: mipsel-uclibc-gcc: not found
make[4]: mipsel-uclibc-gcc: No se encontró el programa
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      kernel/bounds.s
/bin/sh: 1: mipsel-uclibc-gcc: not found
make[5]: *** [/home/cesar/asuswrt-xiaomi/release/src-ra-5010/linux/linux-3.10.14.x/./Kbuild:36: kernel/bounds.s] Error 127
make[4]: *** [Makefile:838: prepare0] Error 2
make[4]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010/linux/linux-3.10.14.x'
make[3]: *** [Makefile:1392: kernel_header] Error 2
make[3]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src/router'
make[2]: *** [Makefile:422: all] Error 2
make[2]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010'
make[1]: *** [Makefile:3945: bin] Error 2
make[1]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010'
make: *** [Makefile:4078: rt-rm2100] Error 2
root@cesar-TP201SA:/home/cesar/asuswrt-xiaomi/release/src-ra-5010#

Hi, tried to build from your sources,but I have that error, Can you help me ? , Im building RM2100 one

**Comment by lukasz1992** [comment]
Please run this command:
`export PATH=/home/cesar/asuswrt-xiaomi/tools/brcm/K26/hndtools-mipsel-uclibc-4.2.4/bin:$PATH`
and then run `make`

**Comment by CessXP** [comment]
> Please run this command:
> `export PATH=/home/cesar/asuswrt-xiaomi/tools/brcm/K26/hndtools-mipsel-uclibc-4.2.4/bin:$PATH`
> and then run `make`

checking for intltool >= 0.35.0... ./configure: line 14648: intltool-update: command not found
 found
configure: error: Your intltool is too old.  You need intltool 0.35.0 or later.
make[3]: *** [Makefile:5629: avahi-0.6.31/Makefile] Error 1
make[3]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src/router'
make[2]: *** [Makefile:422: all] Error 2
make[2]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010'
make[1]: *** [Makefile:3945: bin] Error 2
make[1]: se sale del directorio '/home/cesar/asuswrt-xiaomi/release/src-ra-5010'
make: *** [Makefile:4078: rt-rm2100] Error 2
 
Now I faced that

**Comment by CessXP** [comment]
Thanks, compiled and working c:
