### ISSUE TITLE
Asus AiMesh

### ISSUE THREAD

**Issue by p4c0ga** [lukasz1992/asuswrt-xiaomi#76]
Hi,
Would be possible to include the Asus AiMesh module in the future?

**Comment by lukasz1992** [comment]
For 382 branch it is not possible :( I wonder if WDS settings could possibly help.
I guess it'd be possible if ASUS releases router based on MT7915, but don't know if it happens.

**Comment by p4c0ga** [comment]
> 
> 
> For 382 branch it is not possible :( I wonder if WDS settings could possibly help.
> I guess it'd be possible if ASUS releases router based on MT7915, but don't know if it happens.

https://www.asus.com/es/Content/AiMesh

**Comment by lukasz1992** [comment]
Nice, but none of the specified models are Mediatek-based routers

**Comment by lukasz1992** [comment]
I have not analysed Xiaomi mesh technology.

But if you tested Xiaomi mesh and confirm it works, have shell access and some free time, I could provide you commands to check.

**Comment by p4c0ga** [comment]
> 
> 
> Nice, but none of the specified models are Mediatek-based routers

Thanks is true :(

**Comment by p4c0ga** [comment]
> 
> 
> I have not analysed Xiaomi mesh technology.
> 
> But if you tested Xiaomi mesh and confirm it works, have shell access and some free time, I could provide you commands to check.

Thanks again lukasz, but unfortunelly I don't know Xiaomi mesh tech

**Comment by lukasz1992** [comment]
OK, I just read that WDS works only on WEP and open networks; we do not have alternative :(

Probably you need repeater mode

**Comment by p4c0ga** [comment]
Recently, I have seen this information for openwrt, giving 802.11s support to MT7621 chipsets with MT603, 612 and 615 radios ... 
Would it be possible to enable mesh with this info ? 
It would also be nice to implement 802.11r for fast roaming between mesh nodes. 
Openwrt has the code for all this. 
Thanks uin advance

**Comment by lukasz1992** [comment]
Unfortunately 3.0.0.4.382 branch of AsusWrt does not support Mesh.
AsusWrt also never gave any options for 802.11r/k/v.

I do not use mt76 driver.
