### ISSUE TITLE
Router Redmi AC2100+ASUS Router apk

### ISSUE THREAD

**Issue by Anders73Petrovi4** [lukasz1992/asuswrt-xiaomi#78]
Hi, I noticed that now  asuswrt Router Redmi AC2100 no longer sees the application ASUS Router apk
Any thoughts on how to fix this?

**Comment by lukasz1992** [comment]
Did not tested it on AC2100, but on R3G it works correctly. Did it work before and did the upgrade break it?

**Comment by Anders73Petrovi4** [comment]
Before everything worked, the last update field does not work. Although, the application for android has also been updated, I'll try to check with the old version ASUS Router

**Comment by lukasz1992** [comment]
Did a factory reset after flashing? Does it help?
Does going back to 52289 (without factory reset) make app working?

**Comment by Anders73Petrovi4** [comment]
I did a reset, the ASUS Router apk installed earlier versions, it did not help. I will try to roll back to an earlier firmware of the router, I will write about the results

**Comment by Anders73Petrovi4** [comment]
Hi, ASUS Router app is working again. Excuse for troubling. There was some kind of failure ... Changed the name of the WIFi network on the router and it worked.

**Comment by Anders73Petrovi4** [comment]
Thank you for your work, excellent firmware

**Comment by lukasz1992** [comment]
Thanks!
