### ISSUE TITLE
Indicator operation in RM2100

### ISSUE THREAD

**Issue by iAvoCaTo** [lukasz1992/asuswrt-xiaomi#79]
Hello. I am a user of your firmware on the RM2100 device and noticed that the internet indicator does not work quite correctly. When the Internet is disconnected, the indicator does not go out, but remains on until the router is rebooted or the cable is removed.

I would also like to suggest more correct operation of the indicators as on native firmware, and more specifically:
1) The system indicator is blue when the router is operating, instead of beige.
2) The Internet indicator lights up orange when there is no Internet BUT connected to the cable and blue when connected to the Internet. When you remove the cable, it turns off.

I am even ready to thank financially for such a CORRECT AND INFORMATIVE work of the indicators!

Thank you for your attention, I hope you fix the problem with the Internet indicator and try to implement their correct operation.

**Comment by lukasz1992** [comment]
Hi, could you provide more information:
- Is this a UI indicator or you mean leds in front of the router?
- Does it work correctly on other ASUS router and which model?
- Do 1. and 2. work correctly on ASUS router?

It is possible that enabling bled kernel module will solve it.

**Comment by iAvoCaTo** [comment]
I mean the indicators located on the front of the Redmi AC2100, there are no more diodes besides them. We are talking about a version with 6 antennas. I'm sorry, I didn't quite understand the rest of the questions...

**Comment by lukasz1992** [comment]
Can you confirm that you have white router with 6 antennas and uploaded RT-RM2100_* firmware?

Can you describe me what happens on AsusWRT now when:
- you disconnect WAN
- you have connected WAN and have no Internet access
- you have Internet access

**Comment by lukasz1992** [comment]
I do not understand one thing:

https://github.com/openwrt/openwrt/commit/f3792690c4f0567a8965d82898295b9d50c3bb7e
https://github.com/openwrt/openwrt/commit/53a1fede1f9856b61092ce4693e7610a515d562b

From these descriptions - white RM2100 does not have blue leds

**Comment by lukasz1992** [comment]
Some large reimplementation needs to be done for release/src/router/rc/wanduck.c , too much time for me now.
