### ISSUE TITLE
. /jffs/.asusrouter scripts dont working

### ISSUE THREAD

**Issue by kissmorning** [lukasz1992/asuswrt-xiaomi#82]
I've had this problem before
. /jffs/.asusrouter unfortunately does not work. Latest version software is installed on mi3g router. Can't we make this function any easier?

**Comment by kissmorning** [comment]
![2021-04-15_17-25-54](https://user-images.githubusercontent.com/68402414/114885806-b26b3300-9e0f-11eb-8851-a2fe366e46c9.png)

**Comment by kissmorning** [comment]
![2021-04-15_17-27-41](https://user-images.githubusercontent.com/68402414/114886094-ecd4d000-9e0f-11eb-96fd-b17cee7c3cfe.png)

**Comment by lukasz1992** [comment]
Please do `ls /tmp -la`

**Comment by kissmorning** [comment]
![Uploading 2021-04-15_23-18-35.png…]()

**Comment by kissmorning** [comment]
![2021-04-15_23-18-35](https://user-images.githubusercontent.com/68402414/114933200-178b4c80-9e41-11eb-8e97-9709b77ceb36.png)

**Comment by lukasz1992** [comment]
And `ls -la /jffs`

**Comment by kissmorning** [comment]
![2021-04-16_10-11-22](https://user-images.githubusercontent.com/68402414/114985997-205d3c00-9e9c-11eb-99bd-b1dfd9cf3958.png)

**Comment by lukasz1992** [comment]
You do not have the script.

Please begin it with
```
#!/bin/sh
```

and remember to do `chmod +x /jffs/.asusrouter`
