### ISSUE TITLE
R2100 / RM2100 repeater mode problems

### ISSUE THREAD

**Issue by minax007** [lukasz1992/asuswrt-xiaomi#84]
I have setup my router in "repeater mode" and see following problems:

**1. WIFI connection cannnot be established** 

WiFi signal strength seems to be very weak. 
I couldn't connect to a network to which I can connect via Padavan and OpenWrt. 
The signal deviates between one and three bars out of four which are shown in the configuration menu.
The router positions between the different firmwares (AsusWrt, Padavan and OpenWrt) were always the same. 
Padavan (https://github.com/hanwckf/rt-n56u) has the best WiFi signal strength. OpenWrt (scp07 19.7.7 build from https://drive.google.com/drive/folders/1WTWvOp-6B54hsCDpuo_hf2JKAaUwmZFG) is appr. 80% of it. The actual AsusWrt does not connect at all in repeater mode but the access point is visible. 
It is probably a driver issue. 

**2. LAN IP address other than 192.168.1.1 cannot be set**

When I wanted to set my IP address to 192.168.7.1 LAN cannot connect to the router anymore. 
At 192.168.1.1 it works.

**Comment by lukasz1992** [comment]
2. Seems to be issue with AsusWRT itself; don't know much about the implementation, but perhaps Repeater disables DHCP server at all and relies on primary AP?

1. I need the following - set the same mode on both AsusWRT and Padavan - I need to compare 2 config files in /etc/Wireless for 2 firmwares, could you show content of files here?

**Comment by minax007** [comment]
The configuration is the same. 
- 2,4 GHz network
- Same access point with same password (e. g. "NETWORK" and "password") with WPA2
- Gateway is the IP address of the access point
- DNS 8.8.8.8 and 4.4.4.4
- IP of LAN 192.168.7.1
- SSID and password of repeater (e. g. "NETWORK 2" and "password") with WPA2

There is nothing more I am configuring.

**Comment by minax007** [comment]
I am sorry, but I am not able to retrieve those. 
Maybe someone else who has this router and has more knowledge than me can support us on this.

**Comment by minax007** [comment]
Am I right that I need to get SSH access and then browse to the paths you have mentioned to be able to retrieve those files?
