### ISSUE TITLE
Flash OpenWrt

### ISSUE THREAD

**Issue by Queenston** [lukasz1992/asuswrt-xiaomi#86]
I appreciate your hard, excellent work.
I have the R3G, and I installed AsusWrt(3.0.0.4_382_52290) a while ago.
I want to switch to OpenWrt now, but I'm not sure of the process to do.
How should I proceed to flash OpenWrt to the router safely?

**Comment by minax007** [comment]
I recommend you to install BREED bootloader: 
https://www.youtube.com/watch?v=tuA9erpENp0

Via BREED you can install almost any firmware easily.

**Comment by lukasz1992** [comment]
The fastest way is to flash initramfs to linux partition, like:

wget https://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/openwrt-19.07.7-ramips-mt7621-xiaomi_mir3g-initramfs-kernel.bin
mtd write -i openwrt-19.07.7-ramips-mt7621-xiaomi_mir3g-initramfs-kernel.bin -d linux

After reboot please flash OpenWRT normal sysupgrade

**Comment by Queenston** [comment]
> The fastest way is to flash initramfs to linux partition, like:
> 
> wget https://downloads.openwrt.org/releases/19.07.7/targets/ramips/mt7621/openwrt-19.07.7-ramips-mt7621-xiaomi_mir3g-initramfs-kernel.bin
> mtd write -i openwrt-19.07.7-ramips-mt7621-xiaomi_mir3g-initramfs-kernel.bin -d linux
> 
> After reboot please flash OpenWRT normal sysupgrade

Thank you so much!
It's so simple and it works so well with 'mtd-write' command.
