### ISSUE TITLE
Back to Stock Xiaomi R4A

### ISSUE THREAD

**Issue by MeowCold** [lukasz1992/asuswrt-xiaomi#87]
Dear developer:
I have a problem, and sometimes the delay can suddenly become huge. Other situations can be tolerated, but the network game will become a sudden freeze or prompt to reconnect. I tried to change to a cloud game to solve the problem, but unfortunately there will be lag. Now I am at a loss, is there any way to restore me to the official firmware? I want to see if there are similar problems with the official firmware until I solve the problem.
Thank you

Official firmware address:
http://cdn.cnbj1.fds.api.mi-img.com/xiaoqiang/rom/r4a/miwifi_r4a_all_cddf4_2.28.69.bin

**Comment by minax007** [comment]
Unplug your router. 
Push the "reset"-Button and then plug it back in. 
Wait the "reset"-Button pushed for five seconds until the router LED flashes. 
Then use this software to flash the firmware you have linked to:
http://bigota.miwifi.com/xiaoqiang/tools/MIWIFIRepairTool.x86.zip
Then you are back on stock. 
More detailed information on the procedure can be found on YouTube.

**Comment by lukasz1992** [comment]
@MeowCold I could try to provide you instruction, but can not guarantee that it succeeds; do you want it?

**Comment by MeowCold** [comment]
@lukasz1992 Yes, thank you!

**Comment by lukasz1992** [comment]
Please use scp to upload file to /tmp, as wget is not working yet; then login to console and write:

```
dd if=miwifi_r4a_all_cddf4_2.28.69.bin bs=676 skip=1 of=image
mtd-write -i image -d OS1
reboot -f
```
