### ISSUE TITLE
System Log

### ISSUE THREAD

**Issue by Queenston** [lukasz1992/asuswrt-xiaomi#88]
I installed RT-MIR3G_3.0.0.4_382_52291-geac6f28.trx.
It's functioning normally.
>May 27 01:00:05 disk_monitor: Got SIGALRM...
May 27 04:39:49 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
May 27 12:40:02 ntp: start NTP update
May 27 23:00:06 disk_monitor: Got SIGALRM...
May 27 23:40:08 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
May 28 00:39:59 ntp: start NTP update
May 28 02:40:11 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
May 28 05:40:14 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
May 28 11:40:20 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
May 28 12:39:57 ntp: start NTP update
> 
`kernel: Replay Counter Different in group msg 2 of 2-way handshake!`
I want to know what causes this log and whether it is a normal working log.

**Comment by lukasz1992** [comment]
WiFi driver logs, probably from 5Ghz radio. I assume it is related to powersaving and think you can ignore that message.
If you have any issues I would not anyway help, because I do not know how to improve Mediatek drivers.
