### ISSUE TITLE
Temperature of CPU and amplifier

### ISSUE THREAD

**Issue by garycheah85** [lukasz1992/asuswrt-xiaomi#90]
Hi Lukas, great work to port the Asus wrt to support xiaomi routers. 
I have a xiaomi router pro AC2600 codename MIR3P.

I have been using OpenWRT previously, moved to your asuswrt version last month. All is well and working great.
Recently I monitor the logs

`kernel: EventThermalProtect: HLType = 0, CurrentTemp = 78, Reason = 3
`
The router is warm to touch, having uptime for 20days.
78 degrees Celsius is not too bad.

Is there any command I can run in SSH or scripts to query for temperature? 
Asus-Merlin have temperature display, although not supported on this model.

**Comment by lukasz1992** [comment]
I see some code parts of thermal protection implemented in drivers, but for every driver it is disabled by default (and only mt76x2 driver allow to enable it). Temperature is not exposed to procfs. So currently it is not possible.

AFAIK radio can reduce spatial streams or even disable TX as overheat protection and I guess firmware handles it automatically - only passing info to drv what happened.
