### ISSUE TITLE
Zerotier Install

### ISSUE THREAD

**Issue by p4c0ga** [lukasz1992/asuswrt-xiaomi#92]
I have try to install zerotier on RT-MIR3G_3.0.0.4_382_52291-geac6f28.trx
The Administration-> System menu do not show the option "Enable JFFS custom scripts and configs"
I can't enable JFFS partition
I can't install entware to install zerotier...
I can't run amtm on Asuswrt to enable entware...
Any solution ?

**Comment by lukasz1992** [comment]
JFFS is enabled by default, you should have it mounted on /jffs.

You need than to prepare autorun script and write it into /jffs/.asusrouter file
If you want a script before reboot (to stop services), you can put it in /jffs/.autostop file

Please make both files executable

**Comment by p4c0ga** [comment]
Thanks

**Comment by p4c0ga** [comment]
The error persist, please, clould you help me...
---
admin@RT-MIR3G:/tmp# ./entware-ngu-setup.sh
 Info:  This script was created by ryzhov_al and modified by TeHashX.
 Info:  Thanks @zyxmon & @ryzhov_al for New Generation Entware
 Info:  and @Rmerlin for his awesome firmwares
 Info:  This script will guide you through the Entware installation.
 Info:  Script modifies only "entware" folder on the chosen drive,
 Info:  no other data will be touched. Existing installation will be
 Info:  replaced with this one. Also some start scripts will be installed,
 Info:  the old ones will be saved on partition where Entware is installed
 Info:  like /tmp/mnt/sda1/jffs_scripts_backup.tgz

 *** Error:  Please "Enable JFFS partition" from "Administration > System"
 *** Error:  from router web UI: www.asusrouter.com/Advanced_System_Content.asp
 *** Error:  then reboot router and try again. Exiting...

**Comment by lukasz1992** [comment]
I do not have entware-ngu-setup.sh

**Comment by p4c0ga** [comment]
OK thanks anyway
