### ISSUE TITLE
Problems with install firmware on RM2100

### ISSUE THREAD

**Issue by kilroy98** [lukasz1992/asuswrt-xiaomi#93]
Hello, I'm trying to flash firmware into my router, but for some unknown reason, after flashing firmware 2 LED indicators go out and nothing else happens. Tried all available versions on "Releases" tab and also all three instructions on Wiki, situation does not change.
I have the same problem with installing new versions of AsusWRT Merlin (only version 5.1.1 is installed), but other firmware like OpenWRT, Padavan and (AsusWRT from ferhung-mtk) are loaded without problems after installation.

Nand flash - Toshiba with bad block's on 14 15 768

kernel: Bad eraseblock 14 at 0x0000001c0000
kernel: Bad eraseblock 15 at 0x0000001e0000
kernel: Bad eraseblock 768 at 0x000006000000

P.S. My english is very bad, and i use Google Translate.

**Comment by lukasz1992** [comment]
Hi,

0x1E0000 is used for storing settings in AsusWRT.
0x600000 is the first block of kernel image

in that case, no my images would work. I will think about using other blocks for devices with bad blocks.

**Comment by lukasz1992** [comment]
Could you try to flash this test image: https://easyupload.io/usksny but to first kernel partition (0x200000 not 0x600000) and provide kernel log if it manages to boot?

**Comment by kilroy98** [comment]
I did it, but nothing changed. I also added autoboot.command boot flash 0x200000 and removed it, but router never boots :( Maybe I'm doing something wrong?

**Comment by lukasz1992** [comment]
Are you sure image was flashed to 0x200000? Would be hard to know without UART console (logs) :(

**Comment by kilroy98** [comment]
Unfortunately, I don't have a UART adapter :(
I pick FW 1, is this first kernel partition?
![asd2142Wf@2](https://user-images.githubusercontent.com/13346898/124764001-316a9600-df3d-11eb-8de7-6df76d5e55b8.png)

**Comment by lukasz1992** [comment]
I don't know, you can try both. If nothing works I can not help without UART adapter :(

**Comment by kilroy98** [comment]
I tried both and it still won't load. Sadly. I will need to buy this adapter, but when I can do it I don’t know :(
Thanks for trying to help.

**Comment by lukasz1992** [comment]
The primary problem is with bad blocks in very important places.
I observed problems with Toshiba, ESMT NANDs works better.

**Comment by kilroy98** [comment]
Hi, at last I found the time and was able to connect the UART adapter, although I do not know how to use a soldering iron xD
It's a latest firmvare version.

Breed Xiaomi R3P Pro Keenetic Ultra KN-1810
http://gsmforum.su/showthread.php?t=113926
Sedy Telegram https://t.me/Sedy_Sergey/
Telegram chat https://t.me/Xiaomi3P

DRAM: 128MB
Platform: MediaTek MT7621A ver 1, eco 3
Board: Xiaomi R3P
Clocks: CPU: 880MHz, DDR: 1200MHz, Bus: 293MHz, Ref: 40MHz
Environment variables @ 00060000 on flash bank 0, size 00020000
Flash: Toshiba NAND 128MiB 3.3V 8-bit (128MB) on mt7621-nfi.0
mt7621-nfi.0: Found Fact BBT at block 1023 (offset 0x07fe0000)
mt7621-nfi.0: Block 768 (offset 0x06000000) is marked as bad block in Fact BBT
rt2880-eth: MAC address from EEPROM is invalid, using default settings.
rt2880-eth: Using MAC address 00:0c:43:00:00:01
eth0: MediaTek MT7530 Gigabit switch

Network started on eth0, inet addr 192.168.1.1, netmask 255.255.255.0

Press any key to interrupt autoboot ... 0

Trying to boot firmware from 0x00200000 in flash bank 0 ...
Reading data into memory ...
U-Boot firmware image header detected.
    Image Name:
    Data Size:    14023088 Bytes
    Load Address: 80001000
    Entry Point:  803a6300
Uncompressing data (LZMA) ... done.
Flushing cache ... done.

Starting kernel at 0x803a6300...


LINUX started...

 THIS IS ASIC

SDK 5.0.S.0
Linux version 3.10.14 (root@ubuntu) (gcc version 4.6.3 (Buildroot 2012.11.1) ) #9 SMP Thu Nov 4 16:14:43 CET 2021

 The CPU feqenuce set to 880 MHz
GCMP present
CPU0 revision is: 0001992f (MIPS 1004Kc)
Software DMA cache coherency
Determined physical RAM map:
 memory: 08000000 @ 00000000 (usable)
Initrd not found or empty - disabling initrd
Zone ranges:
  Normal   [mem 0x00000000-0x07ffffff]
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x00000000-0x07ffffff]
Detected 3 available secondary CPU(s)
Primary instruction cache 32kB, 4-way, VIPT, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
PERCPU: Embedded 7 pages/cpu @81103000 s6848 r8192 d13632 u32768
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32512
Kernel command line: console=ttyS1,115200n8 root=/dev/mtdblock5 rootfstype=squashfs noinitrd
PID hash table entries: 512 (order: -1, 2048 bytes)
Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
Writing ErrCtl register=00008080
Readback ErrCtl register=00008080
Memory: 124560k/131072k available (3771k kernel code, 6512k reserved, 1033k data, 244k init, 0k highmem)
Hierarchical RCU implementation.
NR_IRQS:128
console [ttyS1] enabled
Calibrating delay loop... 577.53 BogoMIPS (lpj=1155072)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 512
launch: starting cpu1
launch: cpu1 gone!
CPU1 revision is: 0001992f (MIPS 1004Kc)
Primary instruction cache 32kB, 4-way, VIPT, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
Synchronize counters for CPU 1: done.
launch: starting cpu2
launch: cpu2 gone!
CPU2 revision is: 0001992f (MIPS 1004Kc)
Primary instruction cache 32kB, 4-way, VIPT, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
Synchronize counters for CPU 2: done.
launch: starting cpu3
launch: cpu3 gone!
CPU3 revision is: 0001992f (MIPS 1004Kc)
Primary instruction cache 32kB, 4-way, VIPT, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
Synchronize counters for CPU 3: done.
Brought up 4 CPUs
NET: Registered protocol family 16
release PCIe RST: RALINK_RSTCTRL = 7000000
PCIE PHY initialize
***** Xtal 40MHz *****
start MT7621 PCIe register access
RALINK_RSTCTRL = 7000000
RALINK_CLKCFG1 = 73ffeff8

*************** MT7621 PCIe RC mode *************
pcie_link status = 0x3
RALINK_RSTCTRL= 7000000
*** Configure Device number setting of Virtual PCI-PCI bridge ***
RALINK_PCI_PCICFG_ADDR = 21007f2 -> 21007f2
PCIE0 enabled
PCIE1 enabled
interrupt enable status: 300000
Port 1 N_FTS = 1b105000
Port 0 N_FTS = 1b105000
config reg done
init_rt2880pci done
bio: create slab <bio-0> at 0
vgaarb: loaded
SCSI subsystem initialized
PCI host bridge to bus 0000:00
pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
pci_bus 0000:00: root bus resource [io  0x1e160000-0x1e16ffff]
pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring
pci 0000:00:00.0: BAR 0: can't assign mem (size 0x80000000)
pci 0000:00:01.0: BAR 0: can't assign mem (size 0x80000000)
pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
pci 0000:00:01.0: BAR 8: assigned [mem 0x60100000-0x601fffff]
pci 0000:00:00.0: BAR 1: assigned [mem 0x60200000-0x6020ffff]
pci 0000:00:01.0: BAR 1: assigned [mem 0x60210000-0x6021ffff]
pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff 64bit]
pci 0000:00:00.0: PCI bridge to [bus 01]
pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
pci 0000:02:00.0: BAR 0: assigned [mem 0x60100000-0x601fffff]
pci 0000:00:01.0: PCI bridge to [bus 02]
pci 0000:00:01.0:   bridge window [mem 0x60100000-0x601fffff]
PCI: Enabling device 0000:00:00.0 (0004 -> 0006)
PCI: Enabling device 0000:00:01.0 (0004 -> 0006)
BAR0 at slot 0 = 0
bus=0x0, slot = 0x0
res[0]->start = 0
res[0]->end = 0
res[1]->start = 60200000
res[1]->end = 6020ffff
res[2]->start = 0
res[2]->end = 0
res[3]->start = 0
res[3]->end = 0
res[4]->start = 0
res[4]->end = 0
res[5]->start = 0
res[5]->end = 0
BAR0 at slot 1 = 0
bus=0x0, slot = 0x1
res[0]->start = 0
res[0]->end = 0
res[1]->start = 60210000
res[1]->end = 6021ffff
res[2]->start = 0
res[2]->end = 0
res[3]->start = 0
res[3]->end = 0
res[4]->start = 0
res[4]->end = 0
res[5]->start = 0
res[5]->end = 0
bus=0x1, slot = 0x0, irq=0x4
res[0]->start = 60000000
res[0]->end = 600fffff
res[1]->start = 0
res[1]->end = 0
res[2]->start = 0
res[2]->end = 0
res[3]->start = 0
res[3]->end = 0
res[4]->start = 0
res[4]->end = 0
res[5]->start = 0
res[5]->end = 0
bus=0x2, slot = 0x1, irq=0x18
res[0]->start = 60100000
res[0]->end = 601fffff
res[1]->start = 0
res[1]->end = 0
res[2]->start = 0
res[2]->end = 0
res[3]->start = 0
res[3]->end = 0
res[4]->start = 0
res[4]->end = 0
res[5]->start = 0
res[5]->end = 0
Switching to clocksource MIPS
NET: Registered protocol family 2
TCP established hash table entries: 1024 (order: 1, 8192 bytes)
TCP bind hash table entries: 1024 (order: 1, 8192 bytes)
TCP: Hash tables configured (established 1024 bind 1024)
TCP: reno registered
UDP hash table entries: 256 (order: 1, 8192 bytes)
UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
NET: Registered protocol family 1
4 CPUs re-calibrate udelay(lpj = 1167360)
squashfs: version 4.0 (2009/01/31) Phillip Lougher
jffs2: version 2.2. (NAND) (ZLIB) (RTIME) (c) 2001-2006 Red Hat, Inc.
msgmni has been set to 243
alg: No test for stdrng (krng)
io scheduler noop registered (default)
Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
serial8250: ttyS0 at MMIO 0x1e000d00 (irq = 27) is a 16550A
serial8250: ttyS1 at MMIO 0x1e000c00 (irq = 26) is a 16550A
Ralink gpio driver initialized
brd: module loaded
loop: module loaded
MediaTek Nand driver init, version v2.1 Fix AHB virt2phys error
Allocate 16 byte aligned buffer: 805019c0
Enable NFI Clock
# MTK NAND # : Use HW ECC
NAND ID [98 F1 80 15 F2, 008015f2]
Device not found, ID: 98f1
Not Support this Device!
chip_mode=00000001
Support this Device in MTK table! 98f1
NAND device: Manufacturer ID: 0x98, Chip ID: 0xf1 (Toshiba NAND 128MiB 3,3V 8-bit), 128MiB, page size: 2048, OOB size: 64
[NAND]select ecc bit:4, sparesize :64 spare_per_sector=16
Scanning device for bad blocks
Bad eraseblock 14 at 0x0000001c0000
Bad eraseblock 15 at 0x0000001e0000
Bad eraseblock 768 at 0x000006000000
Signature matched and data read!
load_fact_bbt success 1023
00 00 00 f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[mtk_nand] Line = 4973!
[mtk_nand] Line = 5731!
[mtk_nand] Line = 5737!
[mtk_nand] Line = 5742!
[mtk_nand] Line = 5744!
[mtk_nand] Line = 5747!
[mtk_nand] Line = 5762!
[mtk_nand] Line = 5769!
[mtk_nand] Line = 5782!
[mtk_nand] Line = 5784!
[mtk_nand] Line = 5791!
[mtk_nand] Line = 5800!
[mtk_nand] start find root file system!
[mtk_nand] Line = 5003  hw2->major = da!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 67!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 36!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 4c!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 8d!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = a6!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 25!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = dd!
[mtk_nand] Line = 5006!
[mtk_nand] end find root file system!
[mtk_nand] Line = 5731!
[mtk_nand] Line = 5737!
[mtk_nand] Line = 5742!
[mtk_nand] Line = 5744!
[mtk_nand] Line = 5747!
[mtk_nand] Line = 5762!
[mtk_nand] Line = 5769!
[mtk_nand] Line = 5782!
[mtk_nand] Line = 5784!
[mtk_nand] Line = 5791!
[mtk_nand] Line = 5800!
[mtk_nand] start find root file system!
[mtk_nand] Line = 5003  hw2->major = 7e!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 4c!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = dc!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = 1b!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = f7!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = d3!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5003  hw2->major = a9!
[mtk_nand] Line = 5009!
[mtk_nand] Line = 5014!
[mtk_nand] Line = 5016 rfs_offset = 001AA8C0!
[mtk_nand] Line = 5003  hw2->major = c0!
[mtk_nand] Line = 5006!
[mtk_nand] Line = 5020!
[mtk_nand] Line = 5026!
[mtk_nand] Line = 5032!
partition 4: 200000 3200000
partition 5: 3aa8c0 3055740
[mtk_nand] end find root file system!
Creating 8 MTD partitions on "MT7621-NAND":
0x000000000000-0x000000100000 : "Bootloader"
0x0000001e0000-0x000000200000 : "nvram"
Bad block detected at 0x3c0, oob_buf[0] is 0x0
0x000000100000-0x000000120000 : "Factory"
0x000000120000-0x000000140000 : "Factory2"
0x000000200000-0x000003400000 : "linux"
0x0000003aa8c0-0x000003400000 : "RootFS"
0x000003800000-0x000006000000 : "jffs2"
0x000000000000-0x000007f80000 : "ALL"
Bad block detected at 0x380, oob_buf[0] is 0x0
Bad block detected at 0x3c0, oob_buf[0] is 0x0
Bad block detected at 0xc000, oob_buf[0] is 0x0
[mtk_nand] probe successfully!
IMQ driver loaded successfully. (numdevs = 2, numqueues = 1)
        Hooking IMQ after NAT on PREROUTING.
        Hooking IMQ before NAT on POSTROUTING.
PPP generic driver version 2.4.2
PPP BSD Compression module registered
PPP MPPE Compression module registered
NET: Registered protocol family 24
PPTP driver version 0.8.5
rdm_major = 253
GMAC1_MAC_ADRH -- : 0x000088c3
GMAC1_MAC_ADRL -- : 0x9741d05f
Ralink APSoC Ethernet Driver Initilization. v3.1  1024 rx/tx descriptors allocated, mtu = 1500!
GMAC1_MAC_ADRH -- : 0x000088c3
GMAC1_MAC_ADRL -- : 0x9741d05f
PROC INIT OK!
u32 classifier
    Performance counters on
nf_conntrack version 0.5.0 (1946 buckets, 7784 max)
xt_time: kernel timezone is -0000
gre: GRE over IPv4 demultiplexor driver
ip_tables: (C) 2000-2006 Netfilter Core Team
Type=Linux
arp_tables: (C) 2002 David S. Miller
TCP: cubic registered
NET: Registered protocol family 10
ip6_tables: (C) 2000-2006 Netfilter Core Team
NET: Registered protocol family 17
l2tp_core: L2TP core driver, V2.0
l2tp_ppp: PPPoL2TP kernel driver, V2.0
8021q: 802.1Q VLAN Support v1.8
List of all partitions:
1f00            1024 mtdblock0  (driver?)
1f01             128 mtdblock1  (driver?)
1f02             128 mtdblock2  (driver?)
1f03             128 mtdblock3  (driver?)
1f04           51200 mtdblock4  (driver?)
1f05           49493 mtdblock5  (driver?)
1f06           40960 mtdblock6  (driver?)
1f07          130560 mtdblock7  (driver?)
No filesystem could mount root, tried:  squashfs
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(31,5)
