### ISSUE TITLE
OpenVPN Server on Mi4A-Giga

### ISSUE THREAD

**Issue by siankatabg** [lukasz1992/asuswrt-xiaomi#94]
I'm just trying to setup an OpenVPN Server on the Mi4A-Giga router but I'm getting and error: "vpnserver1: Get CA Key failed"

Am I doing something wrong or should I do somnething else (manually by ssh or something)?

**Comment by lukasz1992** [comment]
I haven't tested openvpn on the firmware.
Need to see your config in ui, ovpn profile

**Comment by siankatabg** [comment]
I just switched back to padavan and configured it so I can't do that right now, sorry. 

But I did tried almost all the different combination of options in the ui and it always hangs on preparing the ovpn profile with the above message in the log

**Comment by lukasz1992** [comment]
Please reopen the ticket if when you're ready to test it again

**Comment by siankatabg** [comment]
Sure, thanks. I'll try to do that tonight or tomorrow 👍🏻
