### ISSUE TITLE
求图文教程

### ISSUE THREAD

**Issue by hululu1068** [lukasz1992/asuswrt-xiaomi#95]
按照你的说明，一直重启啊，能否出个图文说明啊。谢谢！

**Comment by underwud1976** [comment]
Please tell me whether there will be a firmware update 3.0.0.4_382_52291 for xiaomi?

**Comment by hululu1068** [comment]
> 请问小米会不会有固件更新3.0.0.4_382_52291？

This is a good idea

**Comment by lukasz1992** [comment]
Guys, english please. I wish there is an update, but it depends on Asus GPL releases
