### ISSUE TITLE
restore stock rom

### ISSUE THREAD

**Issue by maximusngx** [lukasz1992/asuswrt-xiaomi#96]
how to restore or getback to default rom?

**Comment by lukasz1992** [comment]
Depends on device. Which one do you have?

**Comment by maximusngx** [comment]
> Depends on device. Which one do you have?

I'm using Redmi AC2100

**Comment by lukasz1992** [comment]
Probably you need to follow this:
https://openwrt.org/toh/xiaomi/xiaomi_redmi_router_ac2100#stock_recovery

**Comment by underwud1976** [comment]
And when will the update be?

**Comment by lukasz1992** [comment]
I do not understand
