### ISSUE TITLE
New 802.11k and 802.11r support maybe dont working.

### ISSUE THREAD

**Issue by CessXP** [lukasz1992/asuswrt-xiaomi#98]
Just updated to newest release, testing 802.11k and 802.11r
I noticed this:
in 5Ghz
![image](https://user-images.githubusercontent.com/31802781/141518619-d363af56-7bf0-4322-8cad-a94adc62b3fc.png)
and 2.4Ghz
![image](https://user-images.githubusercontent.com/31802781/141518662-4ac08f85-f62c-43ad-8245-b78a59406dee.png)

Are  802.11k and 802.11r support working ok?

**Comment by lukasz1992** [comment]
I only enabled them in driver in 04ff77e5, this means driver in theory should support it.

But I have not found how to enable options in ASUS interface, maybe it is impossible without manual scripts. I can not test it too.

**Comment by CessXP** [comment]
Ok, thanks, have a good day.
