### ISSUE TITLE
Problems with install firmware on RM2100 (x2)

### ISSUE THREAD

**Issue by kilroy98** [lukasz1992/asuswrt-xiaomi#99]
Hi, at last I found the time and was able to connect the UART adapter, although I do not know how to use a soldering iron xD
It's a latest firmware version. (I can't reopen the last commit). Flashed on FW1 and boot set from 0x200000
The text is too big, so I sent it via pastebin:
https://pastebin.com/NubNQXZD

**Comment by kilroy98** [comment]
#93

**Comment by lukasz1992** [comment]
Thanks for this. I see bad blocks on nvram partition - no my image could work :(

Another problem is bad block at 0x600000 - probably this corrupts squashfs filesystem and makes kernel panic.
Kernel tries to mount image from 0x200000 and is able to read squashfs offset correctly.

If bad block is ommited (and image boots) in some kind firmware (assuming driver logic is the same, you could try to flash it from there); maybe bootloader overwrites (and ignores) bad block.


I do not know how other firmwares treat bad sectors, I do not have any such device to test.

**Comment by lukasz1992** [comment]
To sum up - very important blocks are bad - for both config and for filesystem.

**Comment by kilroy98** [comment]
It is sad. Do you have any idea how to solve this problem? Maybe I could install test builds on my router or is this too risky?

**Comment by lukasz1992** [comment]
Which firmware works for your device now? First you need to flash it and then provide kernel log.

Another option is recompiling firmware manually, I will tell you what to change

**Comment by kilroy98** [comment]
Now i use AsusWRT Merlin by paldier and it loading without problems, but only version 5.1.1

**Comment by kilroy98** [comment]
and it's need boot from 0x600000 :/

**Comment by lukasz1992** [comment]
You could try to boot 5.1.1 and show kernel log.

**Comment by kilroy98** [comment]
I can only give logs from the system log on the WEB, because uart introduces hieroglyphs and similar characters: "Starting kernel at 0x803a7f50...

怘▒▒▒▒ff▒▒~▒▒~fx▒▒▒怘▒怘▒f▒▒▒▒▒▒▒▒f▒f▒▒▒怘"

https://pastebin.com/55Kb1cWS

**Comment by kilroy98** [comment]
I can try to flash the AsusWRT from ferhung-mtk, it also boots without problems.

**Comment by kilroy98** [comment]
It's logs from ferhung-mtk version of AsusWRT, but in UART logs i see the same symbols as on Merlin when the firmware is loaded
https://pastebin.com/RmYYfrq7

**Comment by lukasz1992** [comment]
OK, these have Xiaomi partition layout. Mine has only Asus compatible.

**Comment by kilroy98** [comment]
I understand that there is no point in wasting time trying to adapt the firmware for shitty memory from Toshiba? :(

**Comment by lukasz1992** [comment]
For me not at all - as I have only one Xiaomi device (no Toshiba NAND).
Other option is to implement custom updater with many lines of code.

**Comment by kilroy98** [comment]
It's sad, but thanks for your time.

I flashed the files that were created for Breed (I can provide them to you), maybe this is also the case, but no one tells how to create *.bin from *.trx . But your firmware still does not load if you flash such an image. :(

**Comment by lukasz1992** [comment]
Binary files do not help. bin/trx all the same.

**Comment by kilroy98** [comment]
I tried to flash Merlin trx version 5.1.1 and the router also does not boot, more precisely, it starts loading, but does not load further. Very strange. Okay, thanks for your time
